import { describe, expect, it, vi } from 'vitest';
import { readFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';

import { moduleFromApi, moduleToApi } from './apiMappers';
import { parseGenerated } from './openapi/generated/types';
import type { CatalogModule } from './openapi/generated/types';

// #497 T8 — the React readback: the module wire the server served (golden,
// generated by the Go chain test on a real PostgreSQL) parses against the
// generated contract, maps into the domain, and re-emits byte-identical
// parameter definitions. That is the "React can later read the same
// normalized definition" link: load → edit-adjacent round-trip → save never
// drifts the authored contract.
describe('furniture authoring cross-surface readback (#497 T8)', () => {
  const fixture = JSON.parse(
    readFileSync(
      fileURLToPath(new URL('../../../contracts/furnitureAuthoringCrossSurface.fixture.json', import.meta.url)),
      'utf8',
    ),
  ) as {
    readonly expected: { readonly moduleServed: Record<string, unknown> };
  };
  const served = fixture.expected.moduleServed;

  it('the served module validates against the generated CatalogModule contract', () => {
    const parsed = parseGenerated<CatalogModule>('CatalogModule', served);
    expect(parsed.id).toBe('f4970000-0000-0000-0000-0000000001a1');
    expect(parsed.parameter_definitions?.length).toBe(5);
  });

  it('maps into the domain and re-emits identical parameter definitions', () => {
    const mod = moduleFromApi(served);
    expect(mod.parameterDefinitions?.length).toBe(5);
    const reEmitted = moduleToApi(mod);
    expect(reEmitted.parameter_definitions).toEqual(served.parameter_definitions);
  });

  it('accepts a write whose optional fields are unset (undefined keys never reach the wire)', async () => {
    // Regression for the #497 T8 browser-gate find: a module whose component
    // carries no placementOverride/overrides and whose hardware line has no
    // fixed id must pass the generated write validation — JSON.stringify
    // drops undefined keys and the validator must mirror that wire.
    const { GraneteApiClient } = await import('./apiClient');
    const sentBodies: string[] = [];
    const fetchSpy = vi.fn(async (_url: unknown, init?: RequestInit) => {
      sentBodies.push(String(init?.body));
      return {
        ok: true,
        status: 201,
        json: async () => served,
        text: async () => '',
      } as Response;
    });
    const client = new GraneteApiClient('http://test', fetchSpy as unknown as typeof fetch);
    // Reaching the wire at all proves the body schema accepted the payload.
    await client.createCatalogModule('token', moduleToApi(moduleFromApi({
      ...served,
      components: [{ componentId: 'f4970000-0000-0000-0000-000000000101', quantity: 1 }],
      hardware_lines: [{ id: 'h1', quantity: 2, option_role: 'BISAGRA' }],
    })) as never);
    expect(sentBodies).toHaveLength(1);
    const wire = JSON.parse(sentBodies[0]!) as {
      components: ReadonlyArray<Record<string, unknown>>;
      hardware_lines: ReadonlyArray<Record<string, unknown>>;
    };
    expect(wire.components[0]).toEqual({
      componentId: 'f4970000-0000-0000-0000-000000000101',
      quantity: 1,
    });
    expect(wire.hardware_lines[0]?.hardware_id).toBe('');
  });

  it('keeps the explicit false and empty-string defaults through the round-trip', () => {
    const mod = moduleFromApi(served);
    const softClose = mod.parameterDefinitions?.find((p) => p.name === 'softClose');
    const clientNote = mod.parameterDefinitions?.find((p) => p.name === 'clientNote');
    expect(softClose?.defaultValue).toBe(false);
    expect(clientNote?.defaultValue).toBe('');
    const reEmitted = moduleToApi(mod).parameter_definitions as ReadonlyArray<Record<string, unknown>>;
    expect(reEmitted.find((p) => p.name === 'softClose')?.defaultValue).toBe(false);
    expect(reEmitted.find((p) => p.name === 'clientNote')?.defaultValue).toBe('');
  });
});
