import type {
  Asset,
  ComponentDefinition,
  FurnitureDefinition,
  HardwareDefinition,
  MaterialDefinition,
} from "./smartFurnitureDomain";

export interface PilotFurniturePreset {
  readonly presetId: string;
  readonly name: string;
  readonly category: "base" | "wall" | "tall";
  readonly furnitureDefinitionId: string;
  readonly parameters: Readonly<Record<string, string | number | boolean>>;
  readonly thumbnailAssetId?: string;
}

export const pilotAssets: Readonly<Record<string, Asset>> = {
  "asset-melamine-white": {
    assetId: "asset-melamine-white",
    name: "Melamina Blanca",
    defaultFormat: "texture_pbr",
    uri: "granete://pilot/materials/melamine-white",
    representations: [
      {
        format: "texture_pbr",
        uri: "granete://pilot/materials/melamine-white/pbr",
        purpose: "rendering",
      },
    ],
    visualProperties: { colorHex: "#F5F5F2", roughness: 0.58, metalness: 0 },
  },
  "asset-oak-light": {
    assetId: "asset-oak-light",
    name: "Roble Claro",
    defaultFormat: "texture_pbr",
    uri: "granete://pilot/materials/oak-light",
    representations: [
      {
        format: "texture_pbr",
        uri: "granete://pilot/materials/oak-light/pbr",
        purpose: "rendering",
      },
    ],
    visualProperties: { roughness: 0.5, metalness: 0 },
  },
  "asset-hinge-generic-110": {
    assetId: "asset-hinge-generic-110",
    name: "Bisagra Genérica 110°",
    defaultFormat: "sketchup_component",
    uri: "granete://pilot/hardware/hinge-110.skp",
    representations: [
      {
        format: "sketchup_component",
        uri: "granete://pilot/hardware/hinge-110.skp",
        purpose: "authoring",
        lod: "lod1",
      },
      {
        format: "glb",
        uri: "granete://pilot/hardware/hinge-110.glb",
        purpose: "realtime_3d",
        lod: "lod0",
      },
    ],
  },
  "asset-slide-generic-500": {
    assetId: "asset-slide-generic-500",
    name: "Corredera Telescópica Genérica 500mm",
    defaultFormat: "sketchup_component",
    uri: "granete://pilot/hardware/slide-500.skp",
    representations: [
      {
        format: "sketchup_component",
        uri: "granete://pilot/hardware/slide-500.skp",
        purpose: "authoring",
        lod: "lod1",
      },
      {
        format: "glb",
        uri: "granete://pilot/hardware/slide-500.glb",
        purpose: "realtime_3d",
        lod: "lod0",
      },
    ],
  },
  "asset-handle-128": {
    assetId: "asset-handle-128",
    name: "Jaladera Recta 128mm",
    defaultFormat: "sketchup_component",
    uri: "granete://pilot/hardware/handle-128.skp",
    representations: [
      {
        format: "sketchup_component",
        uri: "granete://pilot/hardware/handle-128.skp",
        purpose: "authoring",
        lod: "lod1",
      },
    ],
  },
};

export const pilotMaterials: Readonly<Record<string, MaterialDefinition>> = {
  "mat-melamine-white-18": {
    materialId: "mat-melamine-white-18",
    materialCode: "PIL-WHITE-18",
    name: "Melamina Blanca 18mm",
    category: "melamine",
    supplier: "Pilot",
    thicknessMm: 18,
    sheetLengthMm: 2750,
    sheetWidthMm: 1830,
    grainDirection: "none",
    compatibleEdgeBandIds: ["edge-white-1", "edge-white-2"],
    visualAssetId: "asset-melamine-white",
  },
  "mat-oak-light-18": {
    materialId: "mat-oak-light-18",
    materialCode: "PIL-OAK-18",
    name: "Melamina Roble Claro 18mm",
    category: "melamine",
    supplier: "Pilot",
    thicknessMm: 18,
    sheetLengthMm: 2750,
    sheetWidthMm: 1830,
    grainDirection: "length",
    compatibleEdgeBandIds: ["edge-oak-1"],
    visualAssetId: "asset-oak-light",
  },
  "mat-mdf-raw-18": {
    materialId: "mat-mdf-raw-18",
    materialCode: "PIL-MDF-18",
    name: "MDF Crudo 18mm",
    category: "mdf",
    supplier: "Pilot",
    thicknessMm: 18,
    sheetLengthMm: 2440,
    sheetWidthMm: 1220,
    grainDirection: "none",
  },
  "mat-hdf-white-6": {
    materialId: "mat-hdf-white-6",
    materialCode: "PIL-HDF-WHITE-6",
    name: "HDF Blanco 6mm",
    category: "mdf",
    supplier: "Pilot",
    thicknessMm: 6,
    sheetLengthMm: 2440,
    sheetWidthMm: 1220,
    grainDirection: "none",
  },
  "edge-white-1": {
    materialId: "edge-white-1",
    materialCode: "PIL-EDGE-WHITE-1",
    name: "Cintilla ABS Blanca 1mm",
    category: "edgeband",
    thicknessMm: 1,
    grainDirection: "none",
  },
  "edge-white-2": {
    materialId: "edge-white-2",
    materialCode: "PIL-EDGE-WHITE-2",
    name: "Cintilla ABS Blanca 2mm",
    category: "edgeband",
    thicknessMm: 2,
    grainDirection: "none",
  },
  "edge-oak-1": {
    materialId: "edge-oak-1",
    materialCode: "PIL-EDGE-OAK-1",
    name: "Cintilla ABS Roble Claro 1mm",
    category: "edgeband",
    thicknessMm: 1,
    grainDirection: "length",
    visualAssetId: "asset-oak-light",
  },
};

export const pilotHardware: Readonly<Record<string, HardwareDefinition>> = {
  "hinge-generic-softclose-110": {
    hardwareId: "hinge-generic-softclose-110",
    code: "PIL-HINGE-110",
    name: "Bisagra Cazoleta Cierre Lento 110°",
    brand: "Generic",
    category: "hinge",
    assetId: "asset-hinge-generic-110",
    pilotDiameterMm: 35,
    pilotDepthMm: 12.5,
    holeType: "hinge",
    placementRules: { defaultFace: "inside", marginMm: 100, systemLineMm: 37 },
  },
  "slide-generic-500": {
    hardwareId: "slide-generic-500",
    code: "PIL-SLIDE-500",
    name: "Corredera Telescópica 500mm",
    brand: "Generic",
    category: "slide",
    assetId: "asset-slide-generic-500",
    dimensionsMm: [500, 45, 12.7],
    pilotDiameterMm: 4,
    pilotDepthMm: 12,
    holeType: "screw",
    placementRules: { defaultFace: "inside", marginMm: 37, systemLineMm: 37 },
  },
  "handle-straight-128": {
    hardwareId: "handle-straight-128",
    code: "PIL-HANDLE-128",
    name: "Jaladera Recta 128mm",
    brand: "Generic",
    category: "handle",
    assetId: "asset-handle-128",
    dimensionsMm: [160, 20, 28],
    pilotDiameterMm: 5,
    pilotDepthMm: 18,
    holeType: "screw",
    placementRules: { defaultFace: "front", marginMm: 50 },
  },
  "shelf-pin-5": {
    hardwareId: "shelf-pin-5",
    code: "PIL-SHELF-PIN-5",
    name: "Soporte de Entrepaño 5mm",
    brand: "Generic",
    category: "shelf_pin",
    pilotDiameterMm: 5,
    pilotDepthMm: 12,
    holeType: "shelf",
    placementRules: { defaultFace: "inside", marginMm: 37, systemLineMm: 37 },
  },
  "minifix-15": {
    hardwareId: "minifix-15",
    code: "PIL-MINIFIX-15",
    name: "Minifix 15mm",
    brand: "Generic",
    category: "connector",
    pilotDiameterMm: 15,
    pilotDepthMm: 12.5,
    holeType: "minifix",
    placementRules: { defaultFace: "inside", marginMm: 50, systemLineMm: 37 },
  },
  "dowel-8x30": {
    hardwareId: "dowel-8x30",
    code: "PIL-DOWEL-8X30",
    name: "Tarugo 8x30mm",
    brand: "Generic",
    category: "connector",
    dimensionsMm: [8, 8, 30],
    pilotDiameterMm: 8,
    pilotDepthMm: 20,
    holeType: "dowel",
    placementRules: { defaultFace: "inside", marginMm: 50, systemLineMm: 32 },
  },
};

export const pilotComponents: Readonly<Record<string, ComponentDefinition>> = {
  "component-side-panel": {
    componentDefinitionId: "component-side-panel",
    code: "PIL-SIDE",
    name: "Lateral",
    category: "panel_lateral",
    boardLocal: "lateral",
    defaultThicknessMm: 18,
    compatibleHardwareCategories: ["hinge", "slide", "connector", "shelf_pin"],
  },
  "component-bottom-panel": {
    componentDefinitionId: "component-bottom-panel",
    code: "PIL-BOTTOM",
    name: "Piso",
    category: "panel_horizontal",
    boardLocal: "horizontal",
    defaultThicknessMm: 18,
    compatibleHardwareCategories: ["connector"],
  },
  "component-top-panel": {
    componentDefinitionId: "component-top-panel",
    code: "PIL-TOP",
    name: "Techo",
    category: "panel_horizontal",
    boardLocal: "horizontal",
    defaultThicknessMm: 18,
    compatibleHardwareCategories: ["connector"],
  },
  "component-stretcher": {
    componentDefinitionId: "component-stretcher",
    code: "PIL-STRETCHER",
    name: "Travesaño",
    category: "stretcher",
    boardLocal: "horizontal",
    defaultThicknessMm: 18,
    compatibleHardwareCategories: ["connector"],
  },
  "component-shelf": {
    componentDefinitionId: "component-shelf",
    code: "PIL-SHELF",
    name: "Entrepaño",
    category: "shelf",
    boardLocal: "horizontal",
    defaultThicknessMm: 18,
    compatibleHardwareCategories: ["connector", "shelf_pin"],
  },
  "component-back-panel": {
    componentDefinitionId: "component-back-panel",
    code: "PIL-BACK",
    name: "Trasera",
    category: "panel_back",
    boardLocal: "back",
    defaultThicknessMm: 6,
  },
  "component-door-flat": {
    componentDefinitionId: "component-door-flat",
    code: "PIL-DOOR-FLAT",
    name: "Puerta Lisa",
    category: "door",
    boardLocal: "door",
    defaultThicknessMm: 18,
    compatibleHardwareCategories: ["hinge", "handle"],
  },
  "component-door-shaker": {
    componentDefinitionId: "component-door-shaker",
    code: "PIL-DOOR-SHAKER",
    name: "Puerta Shaker",
    category: "door",
    boardLocal: "door",
    defaultThicknessMm: 18,
    compatibleHardwareCategories: ["hinge", "handle"],
  },
  "component-drawer-front": {
    componentDefinitionId: "component-drawer-front",
    code: "PIL-DRAWER-FRONT",
    name: "Frente de Cajón",
    category: "drawer_front",
    boardLocal: "door",
    defaultThicknessMm: 18,
    compatibleHardwareCategories: ["handle"],
  },
  "component-drawer-box": {
    componentDefinitionId: "component-drawer-box",
    code: "PIL-DRAWER-BOX",
    name: "Caja de Cajón",
    category: "drawer_box",
    boardLocal: "custom",
    defaultThicknessMm: 15,
    compatibleHardwareCategories: ["slide"],
  },
};

const carcassAssignments = [
  {
    assignmentId: "pilot-carcass",
    role: "carcass",
    materialId: "mat-melamine-white-18",
    thicknessMm: 18,
    edgeBandId: "edge-white-1",
    edgeBandThicknessMm: 1,
  },
  {
    assignmentId: "pilot-shelf",
    role: "shelf",
    materialId: "mat-melamine-white-18",
    thicknessMm: 18,
    edgeBandId: "edge-white-1",
    edgeBandThicknessMm: 1,
  },
  {
    assignmentId: "pilot-front",
    role: "front",
    materialId: "mat-oak-light-18",
    thicknessMm: 18,
    grainDirection: "length" as const,
    edgeBandId: "edge-oak-1",
    edgeBandThicknessMm: 1,
  },
  {
    assignmentId: "pilot-back",
    role: "back_panel",
    materialId: "mat-hdf-white-6",
    thicknessMm: 6,
  },
] as const;

const dimensionParameters = (width: number, height: number, depth: number) => [
  { name: "widthMm", label: "Ancho", type: "number" as const, defaultValue: width, unit: "mm" as const, min: 300, max: 1200, step: 50, category: "dimension" as const },
  { name: "heightMm", label: "Alto", type: "number" as const, defaultValue: height, unit: "mm" as const, min: 600, max: 2400, step: 10, category: "dimension" as const },
  { name: "depthMm", label: "Fondo", type: "number" as const, defaultValue: depth, unit: "mm" as const, min: 280, max: 650, step: 10, category: "dimension" as const },
];

export const pilotFurnitureDefinitions: Readonly<Record<string, FurnitureDefinition>> = {
  "furniture-base-door": {
    furnitureDefinitionId: "furniture-base-door",
    code: "PIL-BASE-DOOR",
    name: "Gabinete Base con Puerta",
    category: "kitchen_base",
    version: "1.0.0",
    revisionId: "pilot-rev-1",
    parameters: [
      ...dimensionParameters(450, 720, 560),
      { name: "shelfCount", label: "Entrepaños", type: "number", defaultValue: 1, unit: "count", min: 0, max: 4, step: 1, category: "configuration" },
      { name: "doorCount", label: "Puertas", type: "number", defaultValue: 1, unit: "count", min: 1, max: 2, step: 1, category: "configuration" },
      { name: "doorSwing", label: "Apertura", type: "enum", defaultValue: "left", options: ["left", "right", "pair"], category: "configuration" },
      { name: "doorComponentId", label: "Modelo de Puerta", type: "enum", defaultValue: "component-door-flat", options: ["component-door-flat", "component-door-shaker"], category: "style" },
      { name: "joinerySystemId", label: "Sistema de Unión", type: "enum", defaultValue: "minifix-dowel", options: ["minifix-dowel", "dowel-only"], category: "hardware" },
    ],
    componentSlots: [
      { slotId: "left-side", role: "left_side", componentDefinitionId: "component-side-panel", defaultMaterialRole: "carcass" },
      { slotId: "right-side", role: "right_side", componentDefinitionId: "component-side-panel", defaultMaterialRole: "carcass" },
      { slotId: "bottom", role: "bottom_panel", componentDefinitionId: "component-bottom-panel", defaultMaterialRole: "carcass" },
      { slotId: "stretcher", role: "top_stretcher", componentDefinitionId: "component-stretcher", defaultMaterialRole: "carcass" },
      { slotId: "shelf", role: "shelf", componentDefinitionId: "component-shelf", defaultMaterialRole: "shelf", quantityParameter: "shelfCount" },
      { slotId: "door", role: "door", componentDefinitionId: "component-door-flat", defaultMaterialRole: "front", quantityParameter: "doorCount" },
      { slotId: "back", role: "back_panel", componentDefinitionId: "component-back-panel", defaultMaterialRole: "back_panel" },
    ],
    relationshipTemplates: [
      { templateId: "shelf-support", kind: "shelf-support", sourceRole: "shelf", targetRoles: ["left_side", "right_side"], defaultJoinerySystemId: "minifix-dowel" },
    ],
    defaultMaterialAssignments: carcassAssignments,
  },
  "furniture-base-drawers": {
    furnitureDefinitionId: "furniture-base-drawers",
    code: "PIL-BASE-DRAWERS",
    name: "Cajonero Base",
    category: "kitchen_base_drawers",
    version: "1.0.0",
    revisionId: "pilot-rev-1",
    parameters: [
      ...dimensionParameters(600, 720, 560),
      { name: "drawerCount", label: "Cajones", type: "number", defaultValue: 3, unit: "count", min: 2, max: 4, step: 1, category: "configuration" },
      { name: "drawerSlideId", label: "Corredera", type: "enum", defaultValue: "slide-generic-500", options: ["slide-generic-500"], category: "hardware" },
      { name: "handleComponentId", label: "Jaladera", type: "enum", defaultValue: "handle-straight-128", options: ["handle-straight-128"], category: "style" },
      { name: "joinerySystemId", label: "Sistema de Unión", type: "enum", defaultValue: "minifix-dowel", options: ["minifix-dowel", "dowel-only"], category: "hardware" },
    ],
    componentSlots: [
      { slotId: "left-side", role: "left_side", componentDefinitionId: "component-side-panel", defaultMaterialRole: "carcass" },
      { slotId: "right-side", role: "right_side", componentDefinitionId: "component-side-panel", defaultMaterialRole: "carcass" },
      { slotId: "bottom", role: "bottom_panel", componentDefinitionId: "component-bottom-panel", defaultMaterialRole: "carcass" },
      { slotId: "stretcher", role: "top_stretcher", componentDefinitionId: "component-stretcher", defaultMaterialRole: "carcass" },
      { slotId: "drawer-front", role: "drawer_front", componentDefinitionId: "component-drawer-front", defaultMaterialRole: "front", quantityParameter: "drawerCount" },
      { slotId: "drawer-box", role: "drawer_box", componentDefinitionId: "component-drawer-box", defaultMaterialRole: "carcass", quantityParameter: "drawerCount" },
      { slotId: "back", role: "back_panel", componentDefinitionId: "component-back-panel", defaultMaterialRole: "back_panel" },
    ],
    relationshipTemplates: [
      { templateId: "drawer-runner", kind: "drawer-runner", sourceRole: "drawer_box", targetRoles: ["left_side", "right_side"], defaultJoinerySystemId: "slide-generic-500" },
    ],
    defaultMaterialAssignments: carcassAssignments,
  },
  "furniture-wall-door": {
    furnitureDefinitionId: "furniture-wall-door",
    code: "PIL-WALL-DOOR",
    name: "Alacena con Puerta",
    category: "kitchen_wall",
    version: "1.0.0",
    revisionId: "pilot-rev-1",
    parameters: [
      ...dimensionParameters(450, 720, 330),
      { name: "shelfCount", label: "Entrepaños", type: "number", defaultValue: 2, unit: "count", min: 0, max: 5, step: 1, category: "configuration" },
      { name: "doorCount", label: "Puertas", type: "number", defaultValue: 1, unit: "count", min: 1, max: 2, step: 1, category: "configuration" },
      { name: "doorSwing", label: "Apertura", type: "enum", defaultValue: "left", options: ["left", "right", "pair"], category: "configuration" },
      { name: "doorComponentId", label: "Modelo de Puerta", type: "enum", defaultValue: "component-door-flat", options: ["component-door-flat", "component-door-shaker"], category: "style" },
      { name: "joinerySystemId", label: "Sistema de Unión", type: "enum", defaultValue: "minifix-dowel", options: ["minifix-dowel", "dowel-only"], category: "hardware" },
    ],
    componentSlots: [
      { slotId: "left-side", role: "left_side", componentDefinitionId: "component-side-panel", defaultMaterialRole: "carcass" },
      { slotId: "right-side", role: "right_side", componentDefinitionId: "component-side-panel", defaultMaterialRole: "carcass" },
      { slotId: "bottom", role: "bottom_panel", componentDefinitionId: "component-bottom-panel", defaultMaterialRole: "carcass" },
      { slotId: "top", role: "top_panel", componentDefinitionId: "component-top-panel", defaultMaterialRole: "carcass" },
      { slotId: "shelf", role: "shelf", componentDefinitionId: "component-shelf", defaultMaterialRole: "shelf", quantityParameter: "shelfCount" },
      { slotId: "door", role: "door", componentDefinitionId: "component-door-flat", defaultMaterialRole: "front", quantityParameter: "doorCount" },
      { slotId: "back", role: "back_panel", componentDefinitionId: "component-back-panel", defaultMaterialRole: "back_panel" },
    ],
    relationshipTemplates: [
      { templateId: "shelf-support", kind: "shelf-support", sourceRole: "shelf", targetRoles: ["left_side", "right_side"], defaultJoinerySystemId: "minifix-dowel" },
    ],
    defaultMaterialAssignments: carcassAssignments,
  },
  "furniture-tall-pantry": {
    furnitureDefinitionId: "furniture-tall-pantry",
    code: "PIL-TALL-PANTRY",
    name: "Despensa / Torre",
    category: "kitchen_tall",
    version: "1.0.0",
    revisionId: "pilot-rev-1",
    parameters: [
      ...dimensionParameters(600, 2100, 560),
      { name: "shelfCount", label: "Entrepaños", type: "number", defaultValue: 5, unit: "count", min: 3, max: 8, step: 1, category: "configuration" },
      { name: "doorCount", label: "Puertas", type: "number", defaultValue: 2, unit: "count", min: 2, max: 2, step: 1, category: "configuration" },
      { name: "doorComponentId", label: "Modelo de Puerta", type: "enum", defaultValue: "component-door-flat", options: ["component-door-flat", "component-door-shaker"], category: "style" },
      { name: "joinerySystemId", label: "Sistema de Unión", type: "enum", defaultValue: "minifix-dowel", options: ["minifix-dowel", "dowel-only"], category: "hardware" },
    ],
    componentSlots: [
      { slotId: "left-side", role: "left_side", componentDefinitionId: "component-side-panel", defaultMaterialRole: "carcass" },
      { slotId: "right-side", role: "right_side", componentDefinitionId: "component-side-panel", defaultMaterialRole: "carcass" },
      { slotId: "bottom", role: "bottom_panel", componentDefinitionId: "component-bottom-panel", defaultMaterialRole: "carcass" },
      { slotId: "top", role: "top_panel", componentDefinitionId: "component-top-panel", defaultMaterialRole: "carcass" },
      { slotId: "shelf", role: "shelf", componentDefinitionId: "component-shelf", defaultMaterialRole: "shelf", quantityParameter: "shelfCount" },
      { slotId: "door", role: "door", componentDefinitionId: "component-door-flat", defaultMaterialRole: "front", quantityParameter: "doorCount" },
      { slotId: "back", role: "back_panel", componentDefinitionId: "component-back-panel", defaultMaterialRole: "back_panel" },
    ],
    relationshipTemplates: [
      { templateId: "shelf-support", kind: "shelf-support", sourceRole: "shelf", targetRoles: ["left_side", "right_side"], defaultJoinerySystemId: "minifix-dowel" },
    ],
    defaultMaterialAssignments: carcassAssignments,
  },
};

export const pilotFurniturePresets: readonly PilotFurniturePreset[] = [
  { presetId: "base-1-door-left", name: "Gabinete Base 1 Puerta Izquierda", category: "base", furnitureDefinitionId: "furniture-base-door", parameters: { widthMm: 450, heightMm: 720, depthMm: 560, shelfCount: 1, doorCount: 1, doorSwing: "left", doorComponentId: "component-door-flat", joinerySystemId: "minifix-dowel" } },
  { presetId: "base-1-door-right", name: "Gabinete Base 1 Puerta Derecha", category: "base", furnitureDefinitionId: "furniture-base-door", parameters: { widthMm: 450, heightMm: 720, depthMm: 560, shelfCount: 1, doorCount: 1, doorSwing: "right", doorComponentId: "component-door-flat", joinerySystemId: "minifix-dowel" } },
  { presetId: "base-2-doors", name: "Gabinete Base 2 Puertas", category: "base", furnitureDefinitionId: "furniture-base-door", parameters: { widthMm: 800, heightMm: 720, depthMm: 560, shelfCount: 1, doorCount: 2, doorSwing: "pair", doorComponentId: "component-door-flat", joinerySystemId: "minifix-dowel" } },
  { presetId: "base-drawers-2", name: "Cajonero Base 2 Cajones", category: "base", furnitureDefinitionId: "furniture-base-drawers", parameters: { widthMm: 600, heightMm: 720, depthMm: 560, drawerCount: 2, drawerSlideId: "slide-generic-500", handleComponentId: "handle-straight-128", joinerySystemId: "minifix-dowel" } },
  { presetId: "base-drawers-3", name: "Cajonero Base 3 Cajones", category: "base", furnitureDefinitionId: "furniture-base-drawers", parameters: { widthMm: 600, heightMm: 720, depthMm: 560, drawerCount: 3, drawerSlideId: "slide-generic-500", handleComponentId: "handle-straight-128", joinerySystemId: "minifix-dowel" } },
  { presetId: "base-drawers-4", name: "Cajonero Base 4 Cajones", category: "base", furnitureDefinitionId: "furniture-base-drawers", parameters: { widthMm: 600, heightMm: 720, depthMm: 560, drawerCount: 4, drawerSlideId: "slide-generic-500", handleComponentId: "handle-straight-128", joinerySystemId: "minifix-dowel" } },
  { presetId: "wall-1-door-left", name: "Alacena 1 Puerta Izquierda", category: "wall", furnitureDefinitionId: "furniture-wall-door", parameters: { widthMm: 450, heightMm: 720, depthMm: 330, shelfCount: 2, doorCount: 1, doorSwing: "left", doorComponentId: "component-door-flat", joinerySystemId: "minifix-dowel" } },
  { presetId: "wall-1-door-right", name: "Alacena 1 Puerta Derecha", category: "wall", furnitureDefinitionId: "furniture-wall-door", parameters: { widthMm: 450, heightMm: 720, depthMm: 330, shelfCount: 2, doorCount: 1, doorSwing: "right", doorComponentId: "component-door-flat", joinerySystemId: "minifix-dowel" } },
  { presetId: "wall-2-doors", name: "Alacena 2 Puertas", category: "wall", furnitureDefinitionId: "furniture-wall-door", parameters: { widthMm: 800, heightMm: 720, depthMm: 330, shelfCount: 2, doorCount: 2, doorSwing: "pair", doorComponentId: "component-door-flat", joinerySystemId: "minifix-dowel" } },
  { presetId: "tall-pantry-2-doors", name: "Despensa / Torre 2 Puertas", category: "tall", furnitureDefinitionId: "furniture-tall-pantry", parameters: { widthMm: 600, heightMm: 2100, depthMm: 560, shelfCount: 5, doorCount: 2, doorComponentId: "component-door-flat", joinerySystemId: "minifix-dowel" } },
] as const;

export const pilotFurnitureCatalog = {
  assets: pilotAssets,
  materials: pilotMaterials,
  hardware: pilotHardware,
  components: pilotComponents,
  definitions: pilotFurnitureDefinitions,
  presets: pilotFurniturePresets,
} as const;
