import type {
  ComponentDefinition,
  FurnitureDefinition,
  HardwareDefinition,
  MaterialDefinition,
} from "../smartFurnitureDomain";

export const sampleMaterials: Record<string, MaterialDefinition> = {
  "mat-melamine-white-18": {
    materialId: "mat-melamine-white-18",
    materialCode: "EGG-W1100-18",
    name: "Melamina Blanca Egger 18mm",
    category: "melamine",
    thicknessMm: 18,
    sheetLengthMm: 2750,
    sheetWidthMm: 1830,
    grainDirection: "none",
    pricePerUnit: 45.0,
    costPerUnit: 28.0,
  },
  "mat-mdf-raw-18": {
    materialId: "mat-mdf-raw-18",
    materialCode: "MDF-STD-18",
    name: "MDF Crudo 18mm",
    category: "mdf",
    thicknessMm: 18,
    grainDirection: "none",
    pricePerUnit: 38.0,
  },
};

export const sampleComponents: Record<string, ComponentDefinition> = {
  "definition-side-panel": {
    componentDefinitionId: "definition-side-panel",
    code: "PANEL-LAT-18",
    name: "Panel Lateral",
    category: "panel_lateral",
    boardLocal: "lateral",
    defaultThicknessMm: 18,
    compatibleHardwareCategories: ["hinge", "connector", "shelf_pin"],
  },
  "definition-shelf": {
    componentDefinitionId: "definition-shelf",
    code: "SHELF-18",
    name: "Entrepaño",
    category: "shelf",
    boardLocal: "horizontal",
    defaultThicknessMm: 18,
    compatibleHardwareCategories: ["connector", "shelf_pin"],
  },
  "definition-door": {
    componentDefinitionId: "definition-door",
    code: "DOOR-SLAB-18",
    name: "Puerta Lisa",
    category: "door",
    boardLocal: "door",
    defaultThicknessMm: 18,
    compatibleHardwareCategories: ["hinge", "handle"],
  },
  "definition-worktop": {
    componentDefinitionId: "definition-worktop",
    code: "WORKTOP-25",
    name: "Cubierta Escritorio",
    category: "worktop",
    boardLocal: "horizontal",
    defaultThicknessMm: 25,
    compatibleHardwareCategories: ["connector"],
  },
  "definition-leg-panel": {
    componentDefinitionId: "definition-leg-panel",
    code: "LEG-PANEL-18",
    name: "Pata Panel",
    category: "panel_lateral",
    boardLocal: "lateral",
    defaultThicknessMm: 18,
    compatibleHardwareCategories: ["connector", "leg"],
  },
};

export const sampleHardware: Record<string, HardwareDefinition> = {
  "hinge-softclose-110": {
    hardwareId: "hinge-softclose-110",
    code: "HER-BIS-CL",
    name: "Bisagra Cazoleta Cierre Lento 110°",
    category: "hinge",
    pilotDiameterMm: 35,
    pilotDepthMm: 12.5,
    holeType: "hinge",
    placementRules: {
      defaultFace: "inside",
      marginMm: 100,
      systemLineMm: 37,
    },
  },
};

export const kitchenBaseDefinition: FurnitureDefinition = {
  furnitureDefinitionId: "definition-kitchen-base",
  code: "KITCHEN-BASE-600",
  name: "Gabinete Base Estándar",
  category: "kitchen_base",
  version: "1.0.0",
  description: "Módulo inferior de cocina con entrepaños y puertas configurables.",
  parameters: [
    {
      name: "widthMm",
      label: "Ancho (mm)",
      type: "number",
      defaultValue: 600,
      min: 300,
      max: 1200,
      step: 50,
      category: "dimension",
    },
    {
      name: "heightMm",
      label: "Alto (mm)",
      type: "number",
      defaultValue: 720,
      min: 600,
      max: 900,
      step: 10,
      category: "dimension",
    },
    {
      name: "depthMm",
      label: "Fondo (mm)",
      type: "number",
      defaultValue: 590,
      min: 300,
      max: 700,
      step: 10,
      category: "dimension",
    },
    {
      name: "shelfCount",
      label: "Cantidad de Entrepaños",
      type: "number",
      defaultValue: 1,
      min: 0,
      max: 4,
      category: "configuration",
    },
    {
      name: "doorCount",
      label: "Cantidad de Puertas",
      type: "number",
      defaultValue: 1,
      min: 0,
      max: 2,
      category: "configuration",
    },
    {
      name: "joinerySystemId",
      label: "Sistema de Unión",
      type: "enum",
      defaultValue: "minifix-dowel",
      options: ["minifix-dowel", "dowel-only"],
      category: "hardware",
    },
  ],
  componentSlots: [
    {
      slotId: "slot-side-left",
      role: "left_side",
      componentDefinitionId: "definition-side-panel",
      defaultMaterialRole: "carcass",
    },
    {
      slotId: "slot-side-right",
      role: "right_side",
      componentDefinitionId: "definition-side-panel",
      defaultMaterialRole: "carcass",
    },
    {
      slotId: "slot-shelf",
      role: "shelf",
      componentDefinitionId: "definition-shelf",
      defaultMaterialRole: "shelf",
      quantityParameter: "shelfCount",
    },
    {
      slotId: "slot-door",
      role: "door",
      componentDefinitionId: "definition-door",
      defaultMaterialRole: "front",
      quantityParameter: "doorCount",
    },
  ],
  relationshipTemplates: [
    {
      templateId: "rel-template-shelf",
      kind: "shelf-support",
      sourceRole: "shelf",
      targetRoles: ["left_side", "right_side"],
      defaultJoinerySystemId: "minifix-dowel",
    },
  ],
  defaultMaterialAssignments: [
    {
      assignmentId: "asgn-carcass",
      role: "carcass",
      materialId: "mat-melamine-white-18",
      thicknessMm: 18,
    },
    {
      assignmentId: "asgn-shelf",
      role: "shelf",
      materialId: "mat-melamine-white-18",
      thicknessMm: 18,
    },
    {
      assignmentId: "asgn-front",
      role: "front",
      materialId: "mat-melamine-white-18",
      thicknessMm: 18,
    },
  ],
};

export const closetTowerDefinition: FurnitureDefinition = {
  furnitureDefinitionId: "definition-closet-tower",
  code: "CLOSET-TOWER-800",
  name: "Torre de Closet / Vestidor",
  category: "closet",
  version: "1.0.0",
  description: "Torre modular para closet con entrepaños ajustables.",
  parameters: [
    {
      name: "widthMm",
      label: "Ancho (mm)",
      type: "number",
      defaultValue: 800,
      min: 400,
      max: 1200,
      category: "dimension",
    },
    {
      name: "heightMm",
      label: "Alto (mm)",
      type: "number",
      defaultValue: 2100,
      min: 1800,
      max: 2600,
      category: "dimension",
    },
    {
      name: "depthMm",
      label: "Fondo (mm)",
      type: "number",
      defaultValue: 500,
      min: 350,
      max: 650,
      category: "dimension",
    },
    {
      name: "shelfCount",
      label: "Entrepaños",
      type: "number",
      defaultValue: 4,
      min: 0,
      max: 8,
      category: "configuration",
    },
  ],
  componentSlots: [],
  relationshipTemplates: [],
  defaultMaterialAssignments: [
    {
      assignmentId: "asgn-closet-carcass",
      role: "carcass",
      materialId: "mat-melamine-white-18",
      thicknessMm: 18,
    },
  ],
};

export const workstationDeskDefinition: FurnitureDefinition = {
  furnitureDefinitionId: "definition-workstation-desk",
  code: "DESK-1200",
  name: "Escritorio de Trabajo",
  category: "desk",
  version: "1.0.0",
  description: "Mesa / escritorio modular con cubierta y patas de panel.",
  parameters: [
    {
      name: "widthMm",
      label: "Largo (mm)",
      type: "number",
      defaultValue: 1200,
      min: 800,
      max: 2000,
      category: "dimension",
    },
    {
      name: "heightMm",
      label: "Alto (mm)",
      type: "number",
      defaultValue: 750,
      min: 650,
      max: 850,
      category: "dimension",
    },
    {
      name: "depthMm",
      label: "Fondo (mm)",
      type: "number",
      defaultValue: 600,
      min: 450,
      max: 900,
      category: "dimension",
    },
  ],
  componentSlots: [],
  relationshipTemplates: [],
  defaultMaterialAssignments: [
    {
      assignmentId: "asgn-desk-top",
      role: "worktop",
      materialId: "mat-melamine-white-18",
      thicknessMm: 18,
    },
  ],
};
