from pathlib import Path
import json,re,datetime
R=Path('/Users/tiagofur/dev/carpinteria/muebles-audit-360-20260903'); S=R/'source'; A=R/'audit'
base=json.loads((A/'data/backend-audit.json').read_text())
# Each description is source-reviewed; extracted details below expose exact implementation evidence.
rows=[
('POST','/api/auth/login','HandleLogin','Identity session entry','email/password, transport and optional organization slug hint','Public, auth rate limiter; active account/password and selectable membership checks; no-store','Uniform invalid-credentials response; organization hint resolves active scope, multi-membership returns selection-required scope','Creates session/refresh family through issuance helpers and login audit; no business project','Web login; SketchUp now uses device flow rather than credential sharing','No new defect asserted; do not show tokens in portal'),
('POST','/api/auth/select-org','HandleSelectOrg','Select organization in existing session','organization_id generated request','Authenticated session; active membership + active org + nonempty role grants; support sessions denied; no-store','MembershipNotSelectable on forbidden target; tenant actor changed only after authoritative selection','Session scope/token update and required audit share request transaction','Web organization switch; not a SketchUp credential handoff','Current browser tenant cache guarantees require consumer/runtime proof'),
('GET','/api/projects','HandleProjects','List visible quotes/projects','No pagination parameters consumed in handler','RoleCanAccessProjects, then owner filter and manufacturing/cost redaction','Storage scoped list then actor owner filter; no mutation','Read-only full project collection','Web quotes/project dashboards via apiWorkspaceRepository','BE-004 / OPS-08: unbounded heavy response; measured scale UNKNOWN'),
('POST','/api/projects','HandleProjects','Create draft quotation/project','domain.Project JSON; customer/items/material option UUIDs','RoleCanMutateProjects; actor-createdBy and owner resolver; org ownership authorization','Required related IDs validated; status forced draft, default currency MXN; duplicate key conflict','CreateProject persists new aggregate','Web create quote via apiWorkspaceRepository','No route-level durable idempotency wrapper on this legacy aggregate route'),
('PUT','/api/projects/{id}','HandleProjectByID','Save project and legacy status/production-release state','Full domain.Project; id path; status and embedded production_release','Actor ownership; RoleCanMutateProjects normally, RoleCanMarkProduced/reopen permissions for transitions','Preserves installation/org ownership; role-specific produced change; freezes structure pins; checks appended event/closeout gates','UpdateProject replaces aggregate; legacy release fields travel here, not a dedicated release command','Web projectStore patch/changeProjectStatus via saveProject','OP-01 frozen quote price and OP-02 generic physical-state writer; OP-03 optimistic Web success. Dedicated immutable manufacturing release endpoint NOT established'),
('GET','/api/furniture/definitions','HandleFurnitureDefinitions','Catalog definitions for authoring library','Authenticated catalog read; no body','Authenticated user and active organization license; extension allowlisted read','User/org validation, assembles modules and catalog dependencies into definitions response','Read-only catalog hydration','SketchUp catalog provider and generated Web client availability','OPS-07 sequential full-family loads; SU-06 consumer cache staleness'),
('GET','/api/furniture/definitions/{definitionId}/layout','HandleFurnitureDefinitionLayout','Authoritative native furniture layout','definitionId; dimensions query; choice.ROLE material IDs','Authenticated user, active scoped organization license','Module lookup, layoutDimsFromQuery and material-aware resolution; nil module 404; invalid dimensions 400','Pure geometry/domain resolution; no furniture instance created','SketchUp catalog provider layout load','SU-03 consumer fallback on nil layout; real host placement still needs proof'),
('POST','/api/furniture/authoring/resolve','HandleFurnitureAuthoringResolve','Rich stateless authoring/machining resolution','Versioned semantic snapshot JSON; Content-Type application/json; no query parameters','Authenticated user + active license; explicit extension POST allowlist','Strict schema/version/content-type/body/query checks; occurrence identities, relationship intent, preflight and fingerprint','No project/FurnitureInstance persistence; returns accepted/rejected resolution envelope','SketchUp provider has transport; rich authoring UI remains disconnected (SU-04)','SU-04 disconnected interaction; SU-05 compiled machining profile limits; successful API is not enabled operator workflow'),
('POST','/api/projects/{projectId}/designs','HandleProjectDesigns','Create logical design under project','CreateDesignRequest and project UUID; Idempotency-Key','RoleCanMutateProjects and authenticated tenant','UUID validation, generated body; storage owns linked project/Design identity','CreateProjectDesign command with actor/request context and durable receipt','Generated Web/Ruby client; operator usage requires calling UI path evidence','No native UI completion inferred from generated client'),
('PUT','/api/designs/{designId}/working-copy','HandleDesignWorkingCopy','Persist mutable design working copy','UpdateDesignWorkingCopyRequest; base_revision_id, source_type, furniture-instance items and parameters/materials','RoleCanAccessProjects in actual PUT handler (not RoleCanMutateProjects)','Valid design/base/FI/definition UUIDs, source-type enum, storage command validation','Replaces working copy through UpdateDesignWorkingCopy; does not mutate immutable revisions','SketchUp working-copy synchronization; Web generated client','Permission uses access-project predicate; report as actual contract, not presumed escalation without role policy proof'),
('POST','/api/designs/{designId}/revisions','HandleDesignRevisions','Publish immutable revision from working state','PublishDesignRevisionRequest base_revision_id/source_type; Idempotency-Key','RoleCanMutateProjects; auth tenant receipt wrapper','Design/base UUIDs; storage publication checks working items and revision lineage','PublishDesignRevision creates exact immutable revision and audit context','Generated Web/Ruby client; distinct from staged artifact publish','Not equivalent to manufacturing approval/release or machine-compatible outputs'),
('GET','/api/designs/{designId}/revisions/{revisionId}','HandleDesignRevision','Read exact historical revision','designId and revisionId UUIDs','RoleCanAccessProjects with tenant-scoped storage','Exact IDs; errors routed through respondWithDesignError','Read-only immutable selected revision','Web revision surface and SketchUp generated transport','Do not replace selected revision with implicit latest in consumers'),
('POST','/api/designs/{designId}/publish:prepare','HandleDesignPublishPrepare','Start staged immutable revision publication','PrepareDesignPublishRequest.manifest; Idempotency-Key','RoleCanMutateProjects; no-store + durable receipt','Design UUID and ParseDesignPublishManifest; authoritative working-item matching delegated to store','Creates staging session/manifest; lazy expired staging cleanup may leave file orphans on IO failure','SketchUp publication flow; generated client','Preparation alone is not a published revision or manufacturing release'),
('POST','/api/designs/{designId}/publish/{sessionId}:finalize','HandleDesignPublishFinalize','Finalize staged revision only with required artifacts','designId/sessionId UUIDs; Idempotency-Key','RoleCanMutateProjects; no-store + durable receipt; wildcard command dispatch','Required artifact metadata and file existence/size checks before transactional finalize','FinalizeDesignPublish commits immutable revision; retry receipt returns same outcome','SketchUp publish workflow; generated client','Static proof only; real host upload/save/reopen not repeated here'),
('POST','/api/projects/{projectId}/reconciliation','HandleProjectReconciliation','Compare exact quote and design revisions by physical identity','quoteRevisionId/designRevisionId + projectId UUIDs','RoleCanAccessProjects; authenticated tenant storage','Reject invalid UUIDs, cross-project comparison, missing revisions and corrupt snapshots','Read-only deterministic differences/counts; no automatic overwrite/release','Web reconciliation generated client; SketchUp endpoint availability is not UI proof','Comparison does not approve, accept changes or release physical production'),
('POST','/api/projects/{id}/parts/{partId}/advance','HandleAdvancePartOperation','Advance one physical piece operation','operation_type or advance=true; operator_name/machine_id/notes','Production/export/mark-produced role union plus assigned sector; factory-only wrapper','Operation vocabulary/current sequence and part belongs to project; scanner resolves current preassembly op','MutateProjectPartExecutions updates piece plus floor events and readiness under mutation boundary','Web floor queue/scanner through apiWorkspaceRepository','OP-02: separate generic project save path can overwrite dedicated result; endpoint transaction alone is insufficient'),
('POST','/api/projects/{id}/quality/qc/{unitId}','HandleQualityUnitQc','Record furniture-unit QC checklist','checklist[{code,passed}], notes/photo IDs; project/unit path','roleCanManageQuality; factory-only wrapper','Nonempty checklist, valid check codes, unit exists in project; passed state derives from checklist','MutateProjectQuality persists QC record, stamps actor/time and constructs quality view','Web QualityScreen/quality API path; not SketchUp authoring','Does not prove machine inspection or physical quality; no new dedicated-route defect asserted'),
('PUT','/api/projects/{id}/installation','HandleProjectInstallation','Save installation visits/issues/punch work','Installation job command body; project path','roleCanManageInstallation; factory-only wrapper','Domain installation validation and mutation path; generic project PUT preserves stored installation','MutateProjectInstallation persists dedicated job state/events','Web installation editor through apiWorkspaceRepository','Readiness and client closeout remain separate actions, not one generic saved=true'),
('POST','/api/projects/{id}/installation/closeout','HandleProjectInstallationCloseout','Complete installation, record signoff, close project','action complete_installation/sign_off/close; signer and note fields','RoleCanAppendProjectEvent specific to mapped action; factory-only wrapper','All units installed/no open visits for completion; EvaluateCloseoutReadiness for signoff/close; signer required','MutateProjectInstallation emits milestone and closeout state; repeated completion conflict','Web closeout through apiWorkspaceRepository','Physical completion/signature evidence is external; API state not proof customer actually signed'),
('PUT','/api/picking','HandlePickingUpsert','Set material dispatch state for project','project_id, material herrajes/tableros/cintillas, status pendiente/despachado','RoleCanMarkPicking = admin or almacen; authenticated tenant','Allowed material/status, nonempty project ID, project exists; server markedAt/By','UpsertProjectPicking only; does NOT debit stock in this request','Web purchasingStore → apiWorkspaceRepository','BE-002 canonical / WEB-01 corroboration: separate stock/picking writes; control-flow reproduction in defect-proofs.json'),
('POST','/api/stock/movements','HandleStockMovementCreate','Record stock ledger movement or exact dispatch reversal','kind/material_id/type/quantity/project_id/note/reverts_id','RoleCanManageStock = admin or almacen; authenticated tenant','Kind/type and delta validation; linked project; reversal same material/exact amount/original despacho; duplicate reversal conflict','RecordStockMovement updates ledger/balance; actor stamped; no picking status write','Web purchasingStore/stock UI → apiWorkspaceRepository','BE-002 canonical: ordinary retry fresh dispatch not combined with picking receipt; no database failure reproduced here')]

def funcs(path):
 text=path.read_text();ms=list(re.finditer(r'^func (?:\([^\n]*\) )?(\w+)\(',text,re.M));out={}
 for i,m in enumerate(ms):
  end=ms[i+1].start() if i+1<len(ms) else len(text);body=text[m.start():end].rstrip();line=text.count('\n',0,m.start())+1
  out[m.group(1)]=(body,f'{path.relative_to(S)}:{line}-{line+body.count(chr(10))}')
 return out
api={};storage={};domain={}
for p in (S/'backend-go/internal/api').glob('*.go'):
 if not p.name.endswith('_test.go'):api.update(funcs(p))
for p in (S/'backend-go/internal/storage').glob('*.go'):
 if not p.name.endswith('_test.go'):storage.update(funcs(p))
for p in (S/'backend-go/internal/domain').glob('*.go'):
 if not p.name.endswith('_test.go'):domain.update(funcs(p))
clientpaths=[S/'packages/storage/src/apiWorkspaceRepository.ts',S/'packages/storage/src/openapi/generated/client.ts']
clientpaths += list((S/'apps/sketchup-extension/src').rglob('*.rb'))
consumer=[]
for p in clientpaths:
 for n,line in enumerate(p.read_text().splitlines(),1):consumer.append((str(p.relative_to(S)),n,line.strip()))
endpoints=[]
for i,row in enumerate(rows,1):
 method,path,handler,purpose,inp,auth,valid,effect,surface,problem=row
 body,href=api[handler]
 match=next((e for e in base['endpoints'] if e.get('method')==method and any(h['name']==handler for h in e.get('handlers',[]))),None)
 if match is None and handler=='HandleDesignPublishFinalize':match=next(e for e in base['endpoints'] if 'publishCommand' in e.get('path',''))
 if match is None and handler=='HandleFurnitureAuthoringResolve':match=next(e for e in base['endpoints'] if e.get('path')=='/api/furniture/authoring/resolve')
 methods=sorted(set(re.findall(r's\.Store\.(\w+)\(',body)))
 storeEvidence=[{'method':x,'evidence':storage[x][1]} for x in methods if x in storage]
 permissions=sorted(set(re.findall(r'\b(RoleCan\w+|roleCan\w+)\b',body)))
 permissionEvidence=[{'name':x,'evidence':(domain.get(x) or api.get(x))[1]} for x in permissions if x in domain or x in api]
 statuses=sorted(set(re.findall(r'http\.(Status\w+)',body)))
 codeErrors=sorted(set(re.findall(r'openapi\.(ApiErrorCode\w+)',body)))
 domainFns=sorted(set(re.findall(r'(?:domain|engine)\.(\w+)\(',body)))
 # Literal path-family matches are connector evidence, not proof a screen reaches them.
 parts=[x for x in path.split('/') if x and not x.startswith('{') and x!='api']; token=parts[-1].split(':')[0] if parts else ''
 callers=[{'evidence':f'{p}:{n}','excerpt':line[:260]} for p,n,line in consumer if token and token in line and ('/api/' in line or 'this.baseUrl' in line or 'this.request(' in line or "request(" in line or 'encodeURIComponent' in line)][:12]
 tests=[]
 for p in (S/'backend-go/internal/api').glob('*test.go'):
  txt=p.read_text()
  if handler in txt or path in txt:
   for n,line in enumerate(txt.splitlines(),1):
    if handler in line or path in line:tests.append({'evidence':f'{p.relative_to(S)}:{n}','match':line.strip()[:180]});break
 e={'id':f'EP-{i:02d}','method':method,'path':path,'purpose':purpose,'authAndRoles':auth,'tenantScope':'AuthMiddleware validates session/membership and establishes tenant transaction/RLS context; resource-specific storage evidence below. Login is anonymous issuance; select-org explicitly changes actor scope. No live cross-tenant request repeated in this subtask.','input':inp,'validation':valid,'output':{'description':'Authoritative response at handler boundary; exact status and return expressions below (shared-method handlers contain other method branches).','observedStatusSymbols':statuses,'returnExpressions':re.findall(r'^\s*respondWithJSON\([^\n]+',body,re.M)},'errors':{'codeSymbols':codeErrors,'mappingHelpers':sorted(set(re.findall(r'\b(respondWith\w*Error)\(',body))),'limitations':'Status lists include all branches of shared handler; method-specific semantics in description. Error helpers/storage can add errors beyond these direct symbols.'},'domain':domainFns,'dependencies':storeEvidence,'sideEffects':effect,'webAndSketchUp':surface,'callers':callers,'callerEvidenceLimit':'Literal transport matches only; generated availability is not active UI wiring. Surface statement calibrated against existing Web/SketchUp reports.','tests':tests[:12],'testEvidenceLevel':'Source presence only; no endpoint runtime test executed by this inventory worker. Parent runtime reports remain separate.','problems':problem,'evidence':[href]+([match['evidence']] if match else []),'permissionEvidence':permissionEvidence,'registration':match.get('registration') if match else None,'idempotency':match.get('idempotencyWrapper',[]) if match else [],'coverage':'SOURCE_DEEP_REVIEW_WITH_RUNTIME_UNKNOWN','missingProof':['Exact actor/tenant routed happy/denied/stale/retry response for this endpoint not executed here.','Native Web/SketchUp behavior must be taken from runtime-ui.json or explicit host evidence, not inferred from this row.']}
 endpoints.append(e)
D={'baseline':base['snapshot'],'generatedAt':datetime.datetime.now(datetime.timezone.utc).isoformat(),'scope':f'{len(endpoints)} deliberately selected critical demo endpoints, NOT all {len(base["endpoints"])} inventory routes.','method':'Reviewed handler source plus roles, dependency definitions and existing backend/Web/SketchUp/operational reports. Automated extraction adds traceable supporting lines; it is not runtime authorization proof.','endpoints':endpoints,'crossCuttingEvidence':['backend-go/internal/api/middleware.go:139-175','backend-go/internal/domain/rbac.go:45-65','backend-go/internal/domain/rbac.go:170-180'],'reportsUsed':['backend-audit.json','web-inventory.json','sketchup-audit.json','operational-flows.json'],'releaseBoundary':'No new standalone manufacturing release route invented. Legacy production_release crosses generic PUT /api/projects/{id}, covered by OP-02; immutable DesignRevision publish is a distinct concern.','unknowns':['No DB, HTTP invocation, security attack, install or product changes.','15–25 endpoint depth target fulfilled with 20 selected endpoints; 245 others remain inventory-level rather than individually deep-reviewed.','Complete role-by-method/storage-error/runtime exhaustiveness not claimed; explicit remaining proof per row.']}
(A/'data/endpoint-deep-audit.json').write_text(json.dumps(D,indent=2)+'\n')
lines=['# Critical endpoint deep audit','',D['scope'],'',D['method'],'','## Release boundary','',D['releaseBoundary'],'']
for e in endpoints:
 lines += [f'## {e["id"]} — {e["method"]} {e["path"]}','',f'Purpose: {e["purpose"]}',f'Auth/roles: {e["authAndRoles"]}',f'Tenant: {e["tenantScope"]}',f'Input: {e["input"]}',f'Validation: {e["validation"]}',f'Side effects: {e["sideEffects"]}',f'Web/SketchUp: {e["webAndSketchUp"]}',f'Problems: {e["problems"]}','Evidence: '+ '; '.join(e['evidence']),'Storage: '+ '; '.join(f'{d["method"]} ({d["evidence"]})' for d in e['dependencies']),'Responses: '+ '; '.join(x.strip() for x in e['output']['returnExpressions']),'Errors/helpers: '+ ', '.join(e['errors']['codeSymbols']+e['errors']['mappingHelpers']),'Tests: '+ '; '.join(t['evidence'] for t in e['tests']),f'Coverage: {e["coverage"]}. {e["testEvidenceLevel"]}','UNKNOWN: '+' '.join(e['missingProof']),'']
lines += ['## Limits','']+D['unknowns']
(A/'evidence/endpoint-deep-audit.md').write_text('\n'.join(lines)+'\n')
print('endpoints',len(endpoints),'with handler refs',sum(bool(x['evidence']) for x in endpoints),'caller matches',sum(bool(x['callers']) for x in endpoints))
# Final curated transport anchors replace loose family matches above.
client='packages/storage/src/openapi/generated/client.ts'; repo='packages/storage/src/apiWorkspaceRepository.ts'; su='apps/sketchup-extension/src/granete_for_sketchup/'
anchors={1:[(client,116)],2:[(client,119)],3:[(repo,609)],4:[(repo,625)],5:[(repo,639)],6:[(su+'library/catalog_provider.rb',311)],7:[(su+'library/catalog_provider.rb',259)],8:[(su+'library/catalog_provider.rb',279)],9:[(client,185)],10:[(client,190),(su+'connection/project_furniture.rb',104)],11:[(client,193)],12:[(client,194)],13:[(client,195),(su+'connection/design_publish.rb',161)],14:[(client,196),(su+'connection/design_publish.rb',189)],15:[(client,187)],16:[(repo,1001)],17:[(repo,2278)],18:[(repo,1139)],19:[(repo,1164)],20:[(repo,1723)],21:[(repo,1788)]}
access='admin, gerente_ventas, vendedor, ingeniero, produccion, gerente_produccion';mutate='admin, gerente_ventas, vendedor'
roleStrings={3:access,4:mutate,5:'General save: '+mutate+'; produced/reopen use their separate predicates; owner scope still applies',9:mutate,10:access,11:mutate,12:access,13:mutate,14:mutate,15:access,16:'admin, gerente_ventas, gerente_produccion, ingeniero, produccion; sector checks remain',17:'admin, gerente_produccion, produccion',18:'admin, gerente_ventas, gerente_produccion, produccion',19:'complete: admin, gerente_ventas, gerente_produccion, produccion; sign_off/close: admin, gerente_ventas, gerente_produccion',20:'admin, almacen',21:'admin, almacen'}
for i,e in enumerate(endpoints,1):
 e['callers']=[{'evidence':f'{p}:{n}','excerpt':(S/p).read_text().splitlines()[n-1].strip()} for p,n in anchors[i]]
 e['callerEvidenceLimit']='Curated actual transport anchor. Generated client availability alone does not prove an operator screen invokes it.'
 e['roles']=roleStrings.get(i,'No independent role whitelist in this reviewed handler; identity/session/license boundaries above apply. See middleware extension allowlist for restricted token transport.')
 if i in [17,18,19]: e['permissionEvidence'].append({'name':'projectEventAppendRoles','evidence':'backend-go/internal/domain/rbac.go:347-363'})
 e['web']={'status':'SOURCE_CONSUMER' if any(p==repo for p,n in anchors[i]) else 'GENERATED_OR_RELATED_SURFACE_ONLY','description':e['webAndSketchUp'],'runtime':'Not executed for this row by this worker; see runtime-ui.json separately.'}
 e['sketchup']={'status':'SOURCE_TRANSPORT' if any(p.startswith(su) for p,n in anchors[i]) else 'NO_DIRECT_CALLER_ESTABLISHED_IN_THIS_ROW','runtime':'Licensed host run not performed; transport is not workflow completion.'}
 e['dependencyEvidenceLimit']='Methods extracted from full handler; shared GET/POST/PUT handlers include branch-specific methods. Storage references locate implementation, not proof every helper was exhaustively audited.'
D['unknowns'][1]=f'Endpoint depth target fulfilled with {len(endpoints)} selected endpoints; remaining inventory routes are not individually deep-reviewed here.'
D['rolesEvidence']='backend-go/internal/domain/rbac.go:45-65,91-100,117-125,170-199,347-363; union semantics plus per-resource checks.'
(A/'data/endpoint-deep-audit.json').write_text(json.dumps(D,indent=2)+'\n')
# Keep main narrative and append exact caller/role supplement to the human evidence.
text=(A/'evidence/endpoint-deep-audit.md').read_text().replace('20 selected endpoints; 245 others remain inventory-level rather than individually deep-reviewed','21 selected endpoints; remaining routes remain inventory-level rather than individually deep-reviewed')
text+='\n## Curated role and caller anchors\n\n'
for e in endpoints:text+=f'### {e["id"]}\n\nRoles: {e["roles"]}\n\nCallers: '+ '; '.join(x['evidence'] for x in e['callers'])+f'\n\nWeb: {e["web"]["status"]}. SketchUp: {e["sketchup"]["status"]}. '+e['callerEvidenceLimit']+'\n\n'
(A/'evidence/endpoint-deep-audit.md').write_text(text)
