import type { CutPlan } from '../../source/packages/domain/src/index';
export function buildCutPlanFixture(): CutPlan {
  return {
    id: 'cutplan-test-1',
    projectId: 'proj-test-1',
    projectName: 'Cocina Test',
    generatedAt: '2026-08-20T00:00:00.000Z',
    version: 1,
    isFrozen: false,
    config: {
      sawKerfMm: 4,
      trim: { topMm: 10, bottomMm: 10, leftMm: 10, rightMm: 10 },
      deductEdgeBand: true,
      allowRotationNoGrain: true,
      minRemnantWidthMm: 400,
      minRemnantLengthMm: 600,
      preferLongitudinalRips: true,
      cutStrategy: 'cnc-nesting',
      toolSpacingMm: 8,
    },
    sheets: [
      {
        sheetIndex: 0,
        strategy: 'cnc-nesting',
        materialCode: 'MDF18',
        materialName: 'MDF Blanco 18mm',
        sheetWidthMm: 1830,
        sheetLengthMm: 2440,
        thicknessMm: 18,
        pieces: [
          {
            id: 'LAT-01-1-s0',
            partCode: 'LAT-01',
            partName: 'Lateral',
            moduleCode: 'M01',
            labelRef: 'A1',
            materialName: 'MDF Blanco 18mm',
            materialCode: 'MDF18',
            xMm: 10,
            yMm: 10,
            lengthMm: 800,
            widthMm: 500,
            originalLengthMm: 800,
            originalWidthMm: 500,
            grain: 1,
            rotated: false,
            L1: 1,
            L2: 1,
            W1: 0,
            W2: 0,
            thicknessMm: 18,
            sheetIndex: 0,
            stripIndex: 0,
            cutSequenceNumber: 1,
            status: 'pending',
          },
          {
            id: 'SEP-01-1-s0',
            partCode: 'SEP-01',
            partName: 'Separador',
            moduleCode: 'M01',
            labelRef: 'A2',
            materialName: 'MDF Blanco 18mm',
            materialCode: 'MDF18',
            xMm: 900,
            yMm: 10,
            lengthMm: 300,
            widthMm: 400,
            originalLengthMm: 400,
            originalWidthMm: 300,
            grain: 0,
            rotated: true,
            L1: 0,
            L2: 0,
            W1: 0,
            W2: 0,
            thicknessMm: 18,
            sheetIndex: 0,
            stripIndex: 0,
            cutSequenceNumber: 2,
            status: 'pending',
          },
        ],
        remnants: [
          {
            id: 'rem-s0-1',
            sheetIndex: 0,
            xMm: 10,
            yMm: 1400,
            lengthMm: 2400,
            widthMm: 400,
            areaM2: 0.96,
            materialName: 'MDF Blanco 18mm',
            materialCode: 'MDF18',
            isUseful: true,
          },
          {
            id: 'rem-s0-2',
            sheetIndex: 0,
            xMm: 10,
            yMm: 520,
            lengthMm: 100,
            widthMm: 100,
            areaM2: 0.01,
            materialName: 'MDF Blanco 18mm',
            materialCode: 'MDF18',
            isUseful: false,
          },
        ],
        instructions: [],
        netPiecesAreaM2: 0.52,
        grossSheetAreaM2: 4.47,
        usableRemnantAreaM2: 0.96,
        wasteAreaM2: 2.99,
        wastePercent: 66.9,
        yieldPercent: 11.6,
      },
    ],
    stats: {
      totalSheets: 1,
      totalPieces: 2,
      totalGrossAreaM2: 4.47,
      totalNetPiecesAreaM2: 0.52,
      totalUsefulRemnantsAreaM2: 0.96,
      totalWasteAreaM2: 2.99,
      globalWastePercent: 66.9,
      globalYieldPercent: 11.6,
      byMaterial: [],
    },
    usefulRemnants: [],
  };
}

