import json,pathlib
p=pathlib.Path(__file__).with_name('endpoint_semantic_notes.json');d=json.loads(p.read_text()) if p.exists() else {}
def note(names,purpose,auth,validation,effects,file,domain):
 for name in names.split(','):d[name]={'purpose':purpose,'authAndRoles':auth,'validation':validation,'sideEffects':effects,'evidence':[file],'tests':[],'domain':domain}
C='GET autenticado; POST/PUT/DELETE AnyRole RoleCanMutateCatalog(admin/ingeniero)'
M='GET autenticado; POST/PUT/DELETE AnyRole RoleCanMutateModules (predicado distinto de mutate catalog)'
f='backend-go/internal/api/handlers.go'
note('HandleCustomers,HandleCustomerByID','CRUD clientes con owner','GET RoleCanAccessCustomers; POST/PUT/DELETE RoleCanMutateCustomers, además scope owner en individual','GET filtra owner; POST resolve owner create; PUT carga existing y resuelve owner update; DELETE comprueba ownership; JSON dominio; duplicate create409.','Create activo; update; delete desactiva, no hard-delete. Falla lookup o owner inaccesible404.',f,'Sales / customer ownership')
note('HandleEdgeBands,HandleEdgeBandByID','CRUD cantos',C,'Body EdgeBand; id requerido; POST activo; duplicate409; PUT missing404 por substring; GET redacta costos según actorCanViewCosts.','Persistencia catálogo; DELETE desactiva; sin prueba de validación física/material del storage en este bloque.',f,'Catalog / edges')
note('HandleOptionGroups,HandleOptionGroupByID','CRUD grupos de opciones',C,'Body OptionGroup; id requerido; duplicate409; PUT missing404 substring; DELETE error genérico500.','Create/update/delete grupo; no fabricación ni resolución de selección por lectura de este endpoint.',f,'Catalog / options')
note('HandleAgregados,HandleAgregadoByID','CRUD subensambles reutilizables',C,'Body Agregado; POST active; duplicate409; PUT missing404; DELETE missing404/in use409 por texto.','DeleteAgregado, no confundir con desactivación de material; storage decide referencias en uso.','backend-go/internal/api/agregados.go','Catalog / subassemblies')
note('HandleAmbientMaterials,HandleAmbientMaterialByID','CRUD acabados de presentación',C,'Body AmbientMaterial; POST active; duplicate409; PUT missing404; no pricing/redaction en esta entidad.','PUT reemplaza textura y limpia archivo previo best effort; DELETE desactiva. No material de manufactura.','backend-go/internal/api/ambient.go','Presentation / ambient material')
note('HandleAmbientCategories,HandleAmbientCategoryByID','Jerarquía categorías de acabados',C,'Body AmbientCategory; storage placement/name/depth se mapea400; PUT ciclos/self/descendant400; GETmissing404; DELETEchildren409.','Create/update/delete categorías presentación.','backend-go/internal/api/ambient.go','Presentation / category hierarchy')
note('HandleMaterialCategories,HandleMaterialCategoryByID','Jerarquía subgrupos tableros',C,'Body MaterialCategory; placement/name/depth400; PUT self/descendant400; GETmissing404; DELETEchildren409 por substring.','Create/update/delete categorías; no modificar tableros por inferencia.','backend-go/internal/api/materialCategories.go','Catalog / material categories')
note('HandleCategories,HandleCategoryByID','Jerarquía categorías muebles',C,'Body ModuleCategory; placement/name/depth400; PUT ciclos400; DELETEchildren400 (diferente de ambient/material409).','Create/update/delete; códigos de error mayormente texto, no contrato generado.',f,'Catalog / module category')
note('HandleModules,HandleModuleByID','CRUD muebles plantilla',M,'GETlist usa GetFullCatalog y retorna Modules; POST/PUT FurnitureParameterDefinitionsError400; duplicate409; DELETE missing404/inuse409.','PUT/DELETE limpian imagen previa después de persistencia exitosa; no identity de FurnitureInstance.',f,'Catalog / module definition')
note('HandleStructures,HandleStructureByID','CRUD estructuras',M,'Body Structure; create duplicate409; update missing404/duplicate409; delete missing404; no engine.ValidateComponent en este handler.','Create/update/delete estructura, no release manufactura.',f,'Catalog / structure')
note('HandleComponents,HandleComponentByID','CRUD componentes paramétricos',M,'POST/PUT engine.ValidateComponent antes de storage; invalid400; duplicate409; individualmissing404.','Create/update/delete componente; no host mutation de SketchUp.',f,'Catalog / parametric component')
note('HandleProjectTemplates,HandleProjectTemplateByID','CRUD plantillas de cotización','GET RoleCanAccessProjects; POST/PUT/DELETE RoleCanMutateModules','Create moneda por defectoMXN/margin1.35/items[]; PUT monedaMXN/items[], sin mismo defaultmargin; create duplicate409.','Plantilla persistente; PUT readback luego de update; DELETE oktrue, error500.',f,'Sales / quote template')
note('HandleWorkshopSettings','Leer/actualizar ajustes taller','GET autenticado; PUT AnyRole RoleCanAccessSettings','JSON WorkshopSettings; handler delega Upsert sin validación semántica adicional visible.','GET lectura; PUT upsert settings scoped por request context.',f,'Organization / settings')
note('HandleAssignableOwners','Enumerar responsables asignables','RoleCanAssignOwner y claims.OrgID obligatorio','Solo memberships activas; roles elegibles admin/gerente_ventas/vendedor/user; ranking rol para proyección.','Lectura id/name/role; no crea cuentas ni invita miembros.',f,'Sales / ownership assignment')
note('HandleSeed','Sembrar catálogo explícitamente','RoleCanMutateModules, aunque texto error diga solo administradores','No body; routePOST; storage SeedCatalog controla contenido.','Mutación catálogo explícita; no se ejecutó en auditoría.',f,'Catalog / explicit seeding')
note('HandleProjectCalculate','Calcular desglose comercial sin persistir','RoleCanAccessProjects + CanAccessOwnedResourceRoles','id requerido; project404; carga catálogo; engine.CalcProjectBreakdown invalid400; redacción costos por actor.','Retorna breakdown; no actualización Project ni congelación en este handler.',f,'Sales / pricing engine')
p.write_text(json.dumps(d,ensure_ascii=False,indent=2)+'\n')
