import pathlib,json
root=pathlib.Path(__file__).resolve().parents[1];src=root.parent/'source'; ledger={x['id']:x for x in json.loads((src/'feature_list.json').read_text())['features']};rows=[]
def add(id,scope,actual,unknown,refs,runtime='UNKNOWN — no feature-specific execution in this subtask'):
 evidence=[]
 for path,line in refs:
  lines=(src/path).read_text().splitlines();assert 1<=line<=len(lines),(path,line)
  evidence.append({'file':path,'line':line,'excerpt':'\n'.join(lines[line-1:min(line+11,len(lines))]),'basis':'source/test body inspected; not execution'})
 rows.append(dict(id=id,title=ledger[id].get('title',ledger[id].get('name')),scope=scope,ledgerStatus=ledger[id]['status'],acceptance=ledger[id].get('acceptance',[]),actualVsAcceptance=actual,auditDepth='SEMANTIC_SOURCE_REVIEW + targeted test contract inspection; acceptance not exhaustively exercised',sourceStatus='SOURCE_PARTIAL — feature-specific behavior reviewed',status='PARTIAL',runtimeStatus=runtime,preciseUnknown=unknown,nextProof=unknown,evidence=evidence))
D='packages/domain/src/';A='backend-go/internal/api/';S='backend-go/internal/storage/';M='backend-go/db/migration/';R='apps/sketchup-extension/src/granete_for_sketchup/';T='apps/sketchup-extension/test/'
add('F161','Contrato puro de intercambio, no sincronización host persistente','applyAuthoringEnvelope valida migration/schema, replay por fingerprint, base stale, completeness con tombstones y aplica sobre copia. Tests comprueban identidad estable, omisión sin delete y round-trip semántico. El state Map no es receipt durable ni prueba SketchUp real.','Ejecutar suite exacta y round-trip con build host pinneado, no confundir fixture TS con integración de dispositivo.',[(D+'sketchupAuthoringExchange.ts',69),(D+'sketchupAuthoringExchange.test.ts',176),(D+'sketchupAuthoringExchange.test.ts',225)])
add('F162','Derivación de relaciones shelf-support/manual hardware','deriveRelationshipMachining recorre relationships y hardware placements, conserva provenance y fingerprint. Rechaza kinds fuera de shelf-support; tests aíslan mover/quitar entrepaño y cambiar joinery. No es catálogo universal de uniones ni interacción nativa.','Validar catálogo concreto requerido por demo y movimiento en host conectado; máquina no evaluada.',[(D+'sketchupRelationshipMachining.ts',60),(D+'sketchupRelationshipMachining.test.ts',93),(D+'sketchupRelationshipMachining.test.ts',153)])
add('F163','Gate mínimo de manufactura puro','runManufacturingPreflight acumula issues y vacía hardware/machining si blocked; tests cubren colisión, out-of-bounds, profundidad y referencias faltantes. Presencia del gate no implica que todos los exports existentes lo consuman.','Trazar export demo hasta este gate; defectos de drilling legacy impiden extender ready del helper a DXF.',[(D+'sketchupPreflight.ts',266),(D+'sketchupPreflight.test.ts',36),(D+'sketchupPreflight.test.ts',81)])
add('F164','Instanciación paramétrica de dominio','instantiateFurniture valida contrato/parámetros antes de geometría; tests generan gabinete, múltiples entrepaños, closet y escritorio y llaman preflight explícitamente. Alcance de test no prueba disponibilidad de todos esos muebles en catálogo real del taller.','Ejecutar casos contra catálogo comercial seleccionado; confirmar caller aplica preflight antes de output físico.',[(D+'furnitureCompositionEngine.ts',213),(D+'sketchupParametricLibrary.test.ts',19),(D+'sketchupParametricLibrary.test.ts',113)])
add('F165','Reposición pura de HardwarePlacement','repositionHardwarePlacement clona envelope, busca identidad exacta, actualiza offset/rotación/cara y recalcula preflight; éxito depende ready/warning. Tests comprueban aislación y solución de colisión. No existe demostración de herramienta interactiva por esta función.','Conectar y probar gesto real de mover herraje en host; capability/UI puede seguir deshabilitada.',[(D+'sketchupHardwareSync.ts',38),(D+'sketchupHardwareSync.test.ts',15),(D+'sketchupHardwareSync.test.ts',75)])
add('F166','Sesión y catálogo remoto de SketchUp: ledger histórico','Application usa DeviceProvider y RemoteCatalogProvider principal con StaticCatalogProvider de fallback. Por tanto AC histórico email/password + token de 30 días + licencia por usuario no describe runtime actual; SEC-6 y licencia org lo sustituyeron.','Smoke de dispositivo enrolado contra build exacto; fallback no debe presentarse como catálogo remoto autoritativo.',[(R+'application.rb',20),(A+'authoring_resolve.go',68)])
add('F168','Negociación y stale dentro de preflight','Gate deriva requirements y marca REVISION_STALE; override solo degrada MACHINE_CAPABILITY_UNSUPPORTED/REVISION_STALE, no colisiones. Tests negativos capability/version/constraint soportan lógica local. Input server-policy no demuestra durable audit real por sí mismo.','Proof de caller server, persistencia audit y perfil/adaptador/version exactos con readback de máquina.',[(D+'sketchupPreflight.ts',232),(D+'sketchupPreflight.ts',455),(D+'sketchupPreflight.test.ts',205)])
add('F169','Esquema y backfill multi-org','Migraciones080–084 introducen org/membership/scope; metadata final confirma roles en memberships y organization_id. Defaults transitorios y active del AC fueron reemplazados por088/lifecycle; no deben restaurarse.','No reejecutado downgrade del chain histórico; consultar pruebas existentes para cada transición exacta.',[(M+'000080_multi_org_core.up.sql',1),(M+'000088_drop_org_defaults.up.sql',1),(S+'multi_org_migration_test.go',157)])
add('F170','Contexto auth vivo y roles por membership','Middleware reconsulta status canónico de membership/org y roles; storage no depende de users.role. JWT v2 / extensión de 30 días de AC son históricos ante registry y DeviceProvider actuales.','Smoke actual de CLI y device de este baseline; no asumir semántica token antiguo a partir de ledger.',[(A+'middleware.go',236),(S+'organizations.go',232),(A+'middleware_test.go',613)])
add('F171','Aislamiento multi-org y unión roles','Tests fuente verifican customers/projects/catalog/settings y directorio por organización; fixtures TS ejercitan unión. Son pruebas concretas no sólo claims de middleware.','Correlacionar cada endpoint adicional con prueba propia; no generalizar todos los265 endpoints desde cinco familias.',[(S+'multi_org_isolation_test.go',61),(S+'multi_org_isolation_test.go',194),(D+'rbacUnion.test.ts',30)],'Related root pilot gate PASS; individual acceptance not independently rerun here')
add('F172','Platform/Team reemplazados por lifecycle moderno','Provisioning y Team tienen commands, bootstrap explícito, audit y soporte separado; AC desactivar usuarios mezcla términos históricos con membership lifecycle moderno. Cancelación step-up con falso success en Team permanece hallazgo independiente.','UX completa de roles/revoke/offboard con cancelación y fracaso real; no declarar éxito administrativo por toast.',[(A+'organization_lifecycle.go',23),('backend-go/internal/application/organizations.go',168),(A+'orgteam_capabilities_test.go',247)])
add('F174','Infraestructura deployment, no VPS certificado','Docker/Caddy/runbooks presentes y smoke estructural root pasa. Suite backup round-trip usa base scratch; no equivale restaurar despliegue real. Operations audit registra toolchain drift y restore que tolera errores.','Build imágenes y deploy/restore en VPS limpio con dominio/TLS reales; no ejecutados en esta auditoría.', [('docker-compose.prod.yml',1),('scripts/smoke-deploy.sh',1),('backend-go/tests/pilotreadiness/backup_test.go',31)])
add('F175','Ownership y redacción Project','manufacturingOnly devuelve notfound fuera de organización fabricante. Tests comprueban create con org ajena y update que conserva ownership/manufacturing. UPDATE actual excluye reasignación org. Esto no resuelve OP-01/02 del contenido editable por fabricante.','Ejercitar mezcla sales/manufacturing real y generic PUT sensible; no confundir redacción cross-org con autoridad de release.',[(A+'ownership.go',151),(A+'projectOwnership_test.go',201),(S+'projects.go',1157)])
add('F176','Unión roles/tipo org y red conectada legacy','Domain tests pinnean roles por factory/store/dealer y unión; usuarios ya no llevan licencia/rol global. parent_organization_id existe, pero red basada en relaciones/capabilities sigue programa Gate B y no se puede inferir operabilidad comercial completa.','Validar caso network vigente bajo ADR0006 / Gate B, no promocionar antigua tab como red completa.',[(D+'organization.test.ts',34),(D+'organization.test.ts',64),(M+'000089_connected_orgs.up.sql',1)])
add('F177','Retiro columnas de usuario','Migration090 elimina role/license_plan/license_expires_at y metadata final confirma ausencia. Lectura membership une org/status/roles actuales; sectores luego migraron a membership_sectors.','No repetir grep histórico como claim exhaustivo; confirmar serialización de clientes legacy cuando corresponda.',[(M+'000090_drop_deprecated_user_columns.up.sql',5),(S+'organizations.go',164),(M+'000097_membership_sectors.up.sql',62)])
add('F178','Regresiones scan org y gates manufacturing','TestUpdateOrganization modifica nombre y comprueba roundtrip de status; API prueba manufacturingOnly y redacción subprocesses. CLI seed actual scoping por organización y owner vía membership. No demuestra manualmente todos los nueve fixes UI históricos.','Smoke CLI set-license/admin y UI manufacturing multi-rol en entorno exacto; sin depender de ledger.',[(S+'multi_org_isolation_test.go',301),(A+'projectOwnership_test.go',247),(A+'projectOwnership_test.go',319),('backend-go/cmd/admin/main.go',393)])
add('F179','Gate pilot HTTP+PostgreSQL','Suite tiene pruebas crossorg bidireccional, clone independence y pg_dump/restore. Gate root ejecutado PASS en DB dedicada, sin skips; separar ese gate de operación productiva real.','Restore VPS operativo y carga/roles representativos aún no demostrados.', [('backend-go/tests/pilotreadiness/crossorg_test.go',21),('backend-go/tests/pilotreadiness/catalog_test.go',12),('backend-go/tests/pilotreadiness/backup_test.go',31)],'Root evidence/pilot-foundation-proof.log PASS; no new test execution in this subtask')
add('F180','Migraciones sin seed de negocio','TestMigrations_NoBusinessData lista explícita de tablas y falla si hay rows tras migrar; seed CLI es explícito y scoped. Claim descriptivo init nunca escribe DB es incorrecto como regla operacional: init ejecuta tests que migran/escriben bases de prueba.','Mantener DB dedicada al ejecutar init; no afirmar servidor compartido intacto. Test no cubre automáticamente tabla futura no listada.',[(S+'migrations_no_seed_test.go',17),('backend-go/cmd/admin/main.go',393),('init.sh',1)])
add('F181','Clean demo transaccional opt-in','CleanDemoData inicia transacción con rollback diferido y reporta referencias; runSeed identifica org y backfillea owners scoped sin truncate global. Dry-run describe efecto dentro de transacción, no necesariamente bajo rol SQL read-only.','No ejecutar limpieza real durante auditoría; validar lista seed/clean contra datos propios antes de apply.',[(S+'clean_demo.go',57),(S+'clean_demo_test.go',15),('backend-go/cmd/admin/main.go',393)])
add('F182','PKs stock/picking y familias aisladas','Migration091 incluye organization_id en ambas PKs; upsert actual usa conflict target scoped. Tests familias cubren stock/picking/templates/ambient/mutators. Esa corrección no hace atómico picking+stock multi-request.','Separar regresión tenancy de defecto transaccional actual; revisar reconciliación GitHub workflow sin inferir que issues fueron cerradas.',[(M+'000091_org_scoped_stock_picking_pk.up.sql',8),(S+'projectPicking.go',42),(S+'multi_org_isolation_families_test.go',305)])
add('F188','Material rebuild host nativo','update_furniture rechaza Group y material change sin NativeLayout, aísla shared definition con make_unique, rebuild dentro de operación con abort. Parámetro sin cambio material puede seguir fallback; no extender gate material a toda edición.','Repetir host material BODY/FRONT real con IDs/world transform/undo y falla de resolve; no ejecutado aquí.',[(R+'model/furniture_builder.rb',446),(R+'model/furniture_builder.rb',461),(T+'testup/TC_NativeValidationSmoke.rb',147)])
add('F189','Paridad espesor: cobertura contractual distinta de host','Fixture material-aware y pruebas nativas contienen cambio FRONT y aislamiento FI-A/FI-B; helper de rebuild preserva metadata tras render. Root no abrió modelo de usuario para repetir operación.','Reejecutar fixture contractual TS/Go/Ruby exacto y host build pinneado; evidencia histórica no prueba esta instalación.',[(R+'model/furniture_builder.rb',446),(T+'testup/TC_NativeValidationSmoke.rb',75),(T+'testup/TC_NativeValidationSmoke.rb',147)])
add('F190','Validación TestUp/OCL histórica','TestUp fuente contiene jerarquía nativa, espesor por rol, transforms rígidos e independencia de instancias. Documento OCL es interoperabilidad acotada, no autoridad BOM ni CNC. Ninguna assertion fue corrida en host actual por esta subtarea.','Host limpio con build exacto, versión OCL y resultado reproducido; no usar 968 assertions históricas como ejecución actual.',[(T+'testup/TC_NativeValidationSmoke.rb',48),(T+'testup/TC_NativeValidationSmoke.rb',125),(T+'testup/TC_OpenCutListInteropSmoke.rb',1)])
add('F195','Resolve stateless de autoría rica','POST handler valida método/auth/licencia de organización y envelope; respuesta layout/machining versionada no persiste Design. API disponible no prueba caller nativo usando el camino rico: inserción/edición base siguen layout GET según auditoría SketchUp.','Conectar primeros comandos host de relación/herraje y comprobar contrato+rollback real, no basta test de parser.',[(A+'authoring_resolve.go',40),(A+'authoring_resolve_test.go',1),(D+'sketchupAuthoringResolve.contract.test.ts',1)])
add('F197','Provisioning/lifecycle atómicos','OrganizationService valida bootstrap/entitlements, usa WithinTenantTx para org/settings/membership/catalog/audit y readiness. Tests PostgreSQL prueban failure rollback y slug concurrency; esquema canónico sustituye active bool.','No inferir todos los flujos UI por gate backend; cancelación step-up Platform/Team debe conservar feedback honesto.', [('backend-go/internal/application/organizations.go',168),(S+'gate_a_provisioning_test.go',18),(S+'organization_lifecycle_migration_test.go',607)],'Related root Foundation/pilot proof PASS; this review is source/metadata only')
add('F200','Base treatment y cantidad fraccional','Go resuelve modo/altura con contexto y define ZOCLO-AUTO; test consume mismo fixture plinthBaseParity y almacenamiento hardware quantity soporta 0.6. Metadata final double precision confirma tipo, no precio/volumen de proyecto real.','Recalcular demo real con patas/zócalo seleccionado y comparar BOM/export; no ejecutar contra catálogo genérico equivocado.', [('backend-go/internal/domain/engine/base_treatment.go',102),('backend-go/internal/domain/engine/plinthBaseParityContract_test.go',391),(S+'hardware_line_quantity_test.go',15)])
add('F201','Migración legacy batch','Migrator pre-resuelve cada item antes de operación, conserva no resueltos como review y hace un batch con rollback ante fallo interno. Tests afirman que fuente no se borra antes de validar replacement y rename no cambia identidad.','TestUp limpio success/failure/save-reopen/undo; no migrar modelo activo del usuario durante auditoría.',[(R+'migration/migrator.rb',40),(T+'unit/migration/migrator_test.rb',244),(T+'testup/TC_MigrationSmoke.rb',1)])
add('F203','Gate A compuesto ejecutable, no programa completo','Script exige infraestructura, rechaza SKIP, ejecuta OpenAPI/typecheck/tests/smoke/pilot fresh/browser. Root posee CI exact SHA Foundation green y componentes locales pilot + 17 tests browser PASS, no inventar wrapper local completo si no se ejecutó.','Gate B y #460/#461 completos quedan separados; conservar evidencia exacta CI vs ejecución local.', [('scripts/foundation-gate-a.sh',17),('scripts/foundation-gate-a.sh',23),('scripts/foundation-gate-a.sh',39)],'Root evidence/main-checks.json exact-SHA green; local pilot PASS and organization-browser 17/17; wrapper not rerun here')
(root/'data/feature-fragments-extra.json').write_text(json.dumps({'sourceCommit':'316df57c7c3c9d5470b5a3f22b39fffeacfd7676','features':rows,'coverage':{'fragments':len(rows),'method':'Targeted source + test contracts; no product changes/tests/new runtime claims'}},ensure_ascii=False,indent=2)+'\n')
md=['# Revisión semántica suplementaria F161–F203','28 features seleccionadas para complementar la matriz; no altera ledger ni declara COMPLETE. No nuevas ejecuciones.']
for r in rows:md += ['## '+r['id']+' — '+r['title'],r['actualVsAcceptance'],'UNKNOWN / siguiente prueba: '+r['preciseUnknown'],'Evidencia: '+', '.join(f"`{e['file']}:{e['line']}`" for e in r['evidence'])]
(root/'evidence/feature-fragments-extra.md').write_text('\n\n'.join(md)+'\n');print(len(rows))
