from pathlib import Path
import json,hashlib
r=Path(__file__).resolve().parents[1];s=r.parent/'source';p=r/'data/feature-matrix.json';d=json.loads(p.read_text())
rows=[
('FM-01','F056','Project templates omit modern layout fields','HIGH','projectToTemplate and createProjectFromTemplate copy walls and placements only; duplicateProject separately preserves spaces, clearance and countertop settings. The real store persists these template conversions.','A reusable layout template should preserve supported design configuration or explicitly disclose excluded fields.','Reusing a multi-space design may lose its spatial/configuration context; impact inferred from conversion, not reproduced.','Preserve the supported layout contract through template conversion and add save/create/reload comparison with multiple spaces and custom countertop/clearance.','Source: high. End-to-end loss: unverified.',[('packages/domain/src/duplicate.ts',204,235),('packages/domain/src/duplicate.ts',274,313),('packages/domain/src/duplicate.ts',333,380),('apps/web/src/stores/projectStore.ts',1109,1171)],'Run a two-space template round-trip with nondefault clearance/countertop and compare persisted fields.', 'P1'),
('FM-02','F073','Configurable CSV implements fixed presets, not the full historical editor','MEDIUM','The domain exposes delimiter, header, preset and material filter; UI uses these four settings and UTF-8 Blob output. No arbitrary column order or encoding selection exists in this inspected flow.','Historical F073 acceptance asks for column selection/reordering, saved workshop presets and UTF-8/Latin-1 choice; these cannot be promised by the current fixed-preset UI.','Customers needing a custom importer layout may require external edits. Existing fixed CSV presets are not declared broken.','Reconcile the promised export scope with supported presets; implement custom settings only if importer requirements justify them, with exact software import/readback.','Source: high. Customer/importer incompatibility: unverified.',[('packages/domain/src/cutListConfigurableCsv.ts',10,46),('packages/domain/src/cutListConfigurableCsv.ts',125,167),('packages/ui/src/production/CsvExportConfigModal.tsx',33,80)],'Export each supported preset and import into the exact receiving software/version; verify settings persistence only if claimed.', 'P2'),
('FM-03','F128','Project drilling cache omits resolution context and selects the first part owner','HIGH','cacheKey includes module ID and optional custom dimensions, but not the item measurement preset/options/context. Resolution runs once per key, and keyByPartId keeps the first owner across cached variants. Export callers consume these patterns.','Each quote line must derive drilling from its exact resolved part and item configuration, without borrowing another line’s joint context.','Different configurations of the same module could receive incorrect derived placements. Wrong output and physical damage have NOT been reproduced; distinct from the separately reproduced provenance-loss finding.','Key/reconcile drilling by exact line/occurrence and complete resolution context; add two-line differential fixtures before any machine claim.','Incomplete identity: high static confidence. Wrong drilling output: INFERRED.',[('packages/domain/src/projectDrilling.ts',90,180),('apps/web/src/exports/useExportHandlers.ts',433,450),('apps/web/src/exportProductionPack.ts',159,165)],'Resolve two lines sharing a module but differing preset/options/custom dimensions; independently compare each drilling result and then exact software readback.', 'P1'),
('FM-04','F072','Legacy cut preview clamps oversized pieces to fit the sheet','HIGH','The preview packer uses Math.min on each piece dimension against sheet size minus kerf. The production-pack caller invokes this legacy preview with default sheet settings.','An oversized piece should produce an explicit does-not-fit diagnostic or an accurately scaled out-of-sheet representation, not silently shrink to fit.','The PDF can visually suggest feasibility for an oversized part. This concerns the legacy visual preview, not the separate nesting optimizer or a machine export.','Reject or visibly flag oversized parts in the preview and pass actual sheet settings; preserve original dimensions in visualization.','Clamping and caller: high static confidence. Generated PDF interaction: not executed.',[('packages/excel/src/cutPreviewPdfExport.ts',31,33),('packages/excel/src/cutPreviewPdfExport.ts',69,128),('packages/excel/src/cutPreviewPdfExport.ts',134,147),('apps/web/src/exportProductionPack.ts',177,188)],'Render a 3000×500 mm piece on a 2440 mm sheet and assert explicit overflow/diagnostic, then inspect the produced PDF.', 'P1'),
('FM-05','F131','Mounted Web hardware gizmo has no move/rotate event wiring','HIGH','HardwarePlacementGizmo defines handleMove and handleRotate but never calls them. Rendered handles only toggle activeHandle on pointer down/up. FurnitureScene3D mounts this component and passes its change callback.','Visible drag/rotation handles should drive the placement command with snap and observable persisted feedback.','The Web viewport handles cannot mutate placement through this component’s rendered event path. Manual fields, other editors and native SketchUp are outside this finding.','Connect drag/rotation events to the existing placement command path; verify snap, cancellation, undo and saved position in a real viewport before demonstrating hardware manipulation.','Missing callback invocation: high static confidence. Browser gesture proof: not executed.',[('packages/ui/src/preview3d/HardwarePlacementGizmo.tsx',68,152),('packages/ui/src/preview3d/FurnitureScene3D.tsx',514,543)],'In a real WebGL viewport select a hardware placement, drag X/Y and rotate Z, assert changed coordinates, undo and save/reload. Keep manual-input behavior separately tested.', 'P1')]
d['findings']=[]
for id,fid,title,severity,actual,expected,impact,reco,confidence,refs,proof,priority in rows:
 ids=[]
 for n,(file,a,b) in enumerate(refs,1):
  eid=f'{id}-E{n}';ids.append(eid);ls=(s/file).read_text().splitlines();assert b<=len(ls);d['evidenceIndex'][eid]={'file':file,'startLine':a,'endLine':b,'excerpt':'\n'.join(ls[a-1:b]),'fileSha256':hashlib.sha256((s/file).read_bytes()).hexdigest(),'basis':'Exact implementation and caller boundary','reviewLevel':'STATIC_SEMANTIC_FINDING'}
 finding={'id':id,'featureId':fid,'title':title,'severity':severity,'priority':priority,'status':'CONFIRMED_STATIC','confidence':confidence,'currentBehavior':actual,'expectedBehavior':expected,'impact':impact,'recommendation':reco,'evidence':[f'{f}:{a}-{b}' for f,a,b in refs],'evidenceIds':ids,'runtimeStatus':'NOT_REPRODUCED','runtimeProofMissing':proof,'sourceCommit':d['sourceCommit']}
 d['findings'].append(finding)
 f=next(f for f in d['features'] if f['id']==fid);f['relatedFindingIds']=list(dict.fromkeys(f.get('relatedFindingIds',[])+[id]));f['problems']=[title];f['recommendation']=reco
p.write_text(json.dumps(d,ensure_ascii=False,indent=2)+'\n')
with (r/'evidence/feature-matrix.md').open('a') as out:
 out.write('\n## Scoped findings from semantic review\n\nNo new runtime reproduction is claimed.\n\n')
 for f in d['findings']:out.write(f"### {f['id']} — {f['title']}\n\n{f['currentBehavior']}\n\nExpected: {f['expectedBehavior']}\n\nImpact: {f['impact']}\n\nAction: {f['recommendation']}\n\nEvidence: "+', '.join(f['evidence'])+f"\n\nMissing proof: {f['runtimeProofMissing']}\n\n")
print('5 findings written')
