from pathlib import Path
import json,hashlib
base=Path(__file__).resolve().parents[2]; src=base/'source'; out=base/'audit'
rows=[]
def add(file,claim,ranges,missing,scope='Static component behavior; no runtime/UI acceptance certification'):
 p='packages/ui/src/'+file; lines=(src/p).read_text().splitlines(); evidence=[]
 for a,b in ranges:
  assert 1<=a<=b<=len(lines),(p,a,b,len(lines))
  evidence.append(dict(file=p,startLine=a,endLine=b,excerpt='\n'.join(lines[a-1:b])))
 rows.append(dict(file=p,claim=claim,scope=scope,auditDepth='SEMANTIC_SOURCE_REVIEW',evidence=evidence,missingProof=missing,runtimeStatus='NOT_EXECUTED',sourceSha256=hashlib.sha256((src/p).read_bytes()).hexdigest()))
add('catalogs/CatalogPicker.tsx','Filters active catalog entries while preserving a selected inactive entry; searches code/name/subtitle, supports arrow/Enter/Escape search navigation and listbox selection; clearing is wired onMouseDown rather than onClick.',[(70,116),(175,208),(270,290),(335,350)],'Browser keyboard activation of clear, focus restoration, popover clipping and screen-reader combobox semantics remain untested.')
add('catalogs/ambient/AmbientCategoryTree.tsx','Recursive category filtering toggles the selected category; management rows invoke edit/delete callbacks, with deletion rendered only when canDelete permits. This component does not persist or enforce hierarchy validity.',[(20,77),(84,150)],'Caller permissions, cyclic category input handling, keyboard/screen-reader selected-state feedback and server persistence remain unverified.')
add('catalogs/hardware/HardwareMachiningSection.tsx','Edits hardware-owned machining parts and operations immutably; type changes retain ID/offset/face but reset kind-specific defaults. Prevents deleting the last operation, converts numeric inputs with Number, and delegates complete profile validation/persistence to the enclosing form.',[(80,139),(243,300),(382,430)],'Domain validation and save rollback must be proved at parent boundary; no host placement, machining output or physical compatibility claim.')
add('catalogs/materials/MaterialExpandedDetail.tsx','Read-only material detail resolves image and displays dimensions/grain/edge/cost/waste/status. Board price and cost per area are rendered by this child without a hideCosts gate; this alone does not establish unauthorized exposure.',[(24,101)],'Caller visibility and API cost redaction, broken-image UX and responsive detail layout remain unverified.')
add('production/EmbarquesProjectDetail.tsx','Uses supplied labels or locally generated fallback (generation error becomes empty labels). Intercepts foreign item IDs only for loaded transitions, displays cross-project alert and blocks release while alert exists; callback Promise is not awaited.',[(60,112),(134,168)],'Rejected save feedback, exact physical package identity, refreshed authoritative progress and release command integration remain unverified.')
add('production/InstalacionesProjectDetail.tsx','Shows installation summary and customer contact links; loaded project item lines appear En camino, and permitted advance invokes installed using project/item identity. Quantity is displayed but command remains item-line scoped. Job panel receives separate manage and closeout flags.',[(47,70),(133,184)],'Quantity>1 per-unit behavior, rejected transitions, visit integration and authoritative closeout require runtime proof.')
add('production/InstallationJobPanel.tsx','Derives visit/issue/punch/closeout views; gates actions by canManage/canCloseout and domain-derived checks, requires resolution notes/signoff name. Void optional callbacks are followed immediately by clearing local drafts/forms; no child pending/commit acknowledgement is represented.',[(59,86),(282,297),(431,441),(547,560),(582,621)],'Deferred/rejected callback tests must establish draft retention and feedback; authoritative transitions/audit and concurrency are not proved by child gates.')
add('production/ProductionBoardView.tsx','Separates supplied exact CutPlanSheet from legacy simplePack preview; cnc-nesting suppresses guillotine decorations. Exact metrics use sheet yield; optional estimated fill sums source areas and caps at100. Legacy approximation remains linked to existing FM-04, not a machine plan.',[(51,91),(95,117)],'FM-04 remains existing finding; nesting/guillotine golden rendering, invalid dimensions and actual machine import/readback remain unproved.')
add('production/ProductionElevationPreview.tsx','Draws wall elevation from supplied units using offset/bottomZ/dimensions, labels wall and width, distinguishes wall/floor fills and empty wall. Unit key is itemId plus instanceIndex; no editing or persistence.',[(15,40),(66,104)],'SVG legibility at narrow widths, accessible unit detail and parity with exported elevations remain unverified.')
add('production/ProductionIslandPreview.tsx','Draws separate free-placement island elevation with category theme, floor/base clearance, dimensions and space label; includes X/Y/yaw metadata without attempting wall projection.',[(24,55),(114,129)],'Preview/PDF parity, accurate elevations for physical assembly, zoom/contrast and screen-reader output remain unverified.')
add('production/ProductionOrderDispatchPanel.tsx','Scan resolves a module payload itemId or first code/name label match; invokes loaded or packaged transition and immediately emits success text/sound without awaiting callback. Disabling auto-loaded still writes packaged. Cards and load/release summary are item-floor-status based, not independent package mutation.',[(112,199),(260,301),(448,475),(500,544)],'Static optimistic-success gap needs deferred/rejected callback proof; duplicate QR, wrong-project wrapper behavior and per-package authoritative load/release remain unproved.')
add('production/ProductionOrderDocumentsPanel.tsx','Renders document catalog availability/reason/action text; disables downloads while busy, unavailable or lacking callback and invokes supplied handler. Pack can become the primary action; component does not generate or authorize documents.',[(20,118)],'Exact release/revision ownership, download failure, duplicate-click recovery, PDF/DXF/CNC/assembly artifact content remain unverified.')
add('production/ProductionOrderHardwarePanel.tsx','Distinguishes failed hardware rows (null) from empty list, gates export by data/busy, renders quantity and optional cost column controlled by hideCosts. This is read-only requirements display, not picking or stock mutation.',[(20,120)],'Cost authorization upstream, requirements-to-stock reconciliation, export parity and failure recovery remain unverified.')
add('production/ProductionOrderModulesPanel.tsx','Builds read-only module rows and searches identifiers/placement; line-keyed floor-status dropdown is shown only with capability and callback, but exposes every ITEM_FLOOR_STATUS rather than locally constrained next transitions.',[(39,55),(108,125),(143,166)],'Server rejection/rollback, pending-state feedback and qty>1 physical unit status cannot be inferred from this line-level dropdown.')
add('production/ProjectFloorProgressStrip.tsx','Delegates progress to buildProjectFloorSummary; no-items returns null, strip has summarized accessible label and decorative stage list, chip reports active sector or installed. No progress mutations or independent metrics computation.',[(24,40),(70,106)],'Underlying event/quantity truth and browser assistive output are not proved by presentation source.')
add('production/board/ProductionBoardHoverCard.tsx','Null piece hides card; otherwise read-only hover details distinguish saw-cut versus original final measures, grain/rotation and edge sides. Card is absolutely positioned with pointerEvents none and no independent keyboard trigger.',[(12,54)],'Accessible alternative and viewport collision on small boards need browser review; numeric values are trusted supplied cut-plan fields.')
add('production/board/ProductionBoardSvg.tsx','Renders supplied exact piece positions, cut/remnant decorations and separate legacy geometry. Useful remnants require isUseful and area>=0.24. Exact-piece groups wire mouse hover/click but no tabindex or keyboard handler; this is a static keyboard-accessibility gap, not runtime certification.',[(59,105),(267,294),(374,401)],'Keyboard-equivalent piece selection, accessible SVG naming, golden edge orientation and machine accuracy remain unverified.')
add('production/hub/ProductionHubResumenTab.tsx','Displays readiness and domain-summarized material areas/edge lengths; missing cut data shows dashes. Ready-to-cut banner trusts readiness.readyToCut while pack export gates packGenerable/busy/callback; no release authority is established here.',[(118,154),(186,240),(243,299)],'Readiness versus exact released revision/machine profile and approved output needs upstream integration proof; this display cannot certify safe cutting.')
add('production/labels/LabelPrinterConfigSection.tsx','Controlled printer settings expose allowed size presets,203/300DPI,border and JSON versus URL QR format; host field appears for URL, printer name only with raw bridge. Local setting callbacks do not validate device compatibility.',[(51,93),(109,159)],'Persistence, malformed host handling, raw desktop bridge availability and exact printer calibration/readback remain unverified.')
add('production/labels/ModuleLabelsTabContent.tsx','Filters bulto labels and builds QR using unit/package fields and production revision override; cancellation suppresses stale QR completion. ZPL uses filtered labels. Raw print awaits bridge result and reports sent versus error, but has no in-flight button lock. Preview rows are mouse-click only.',[(81,130),(132,154),(156,205),(341,385),(410,420)],'Repeated raw-print clicks, keyboard row selection, QR failure visibility and actual printed label/readback are unverified; bridge acceptance is not physical print proof.')
add('production/labels/PieceLabelsTabContent.tsx','Filters piece labels by text/module/material, optionally expands quantity into copies (minimum1,floor quantity), generates cancellable QR preview and ZPL. Raw print awaits result with status/alert; buttons lack print-in-flight lock and preview rows wire only mouse clicks.',[(50,54),(89,112),(115,152),(180,220),(436,475),(500,510)],'Quantity normalization/identity, double print, keyboard preview selection and exact QR/PDF/ZPL/printer parity need tests; existing FM-03 drilling proof does not prove labels.')
add('production/manager/ProductionManagerActiveJobs.tsx','Read-only activity rows display operator/project/module/machine and formatted supplied duration. Empty jobs hide the section; despite real-time header comment this component owns no refresh clock/subscription.',[(9,40),(48,60)],'Upstream refresh cadence, stale/failed fetch distinction and duration correctness remain unverified.')
add('production/manager/ProductionManagerProjectsTable.tsx','Displays supplied project summaries, prioritizes open-order callback over open-project, renders named progressbar and sector counts. Empty list presents no-project state; no local loading/error distinction or business mutation.',[(30,65),(76,116),(146,166)],'Upstream permission filtering, empty-versus-error distinction, totalItems truth and navigation integration need proof.')
add('production/manager/ProductionManagerSectorsGrid.tsx','Sector buttons report aria-pressed selection and callback, active-operator/queue counts; optional metric panel displays supplied completed/damaged daily totals. Icon fallback covers unknown sector without creating a workflow state.',[(22,38),(64,91),(95,124)],'Metrics actual-versus-proxy provenance, day timezone boundaries and refresh/error behavior remain upstream and unverified.')
assert len(rows)==24
payload=dict(sourceCommit='316df57c7c3c9d5470b5a3f22b39fffeacfd7676',scope='24 secondary production/catalog files; manual bounded semantic source review; no browser/tests/DB/product changes',fragments=rows)
(out/'data/web-secondary-production.json').write_text(json.dumps(payload,indent=2,ensure_ascii=False)+'\n')
(out/'evidence/web-secondary-production.md').write_text('# Secondary production and catalog source review\n\nStatic only; no UI/runtime certification. Existing findings are not duplicated.\n\n'+'\n\n'.join('## '+r['file']+'\n'+r['claim']+'\n\nMissing proof: '+r['missingProof']+'\n\nEvidence: '+', '.join(f"{e['file']}:{e['startLine']}–{e['endLine']}" for e in r['evidence']) for r in rows)+'\n')
print(f'{len(rows)} files; {sum(len(r["evidence"]) for r in rows)} exact validated ranges')
