ALTER TABLE agregados
ADD COLUMN IF NOT EXISTS notes TEXT,
ADD COLUMN IF NOT EXISTS width_mm INT NOT NULL DEFAULT 0,
ADD COLUMN IF NOT EXISTS height_mm INT NOT NULL DEFAULT 0,
ADD COLUMN IF NOT EXISTS depth_mm INT NOT NULL DEFAULT 0,
ADD COLUMN IF NOT EXISTS hardware_lines JSONB NOT NULL DEFAULT '[]'::jsonb;
