#!/usr/bin/env python3
"""Deterministic, dependency-free generator for Granete's bounded OpenAPI v1."""
from __future__ import annotations
import argparse, json, pathlib, re, subprocess

ROOT = pathlib.Path(__file__).resolve().parents[1]
SPEC = ROOT / "contracts/openapi/granete-api.v1.yaml"

def validate_spec(spec):
    if not str(spec.get("openapi", "")).startswith("3.1."):
        raise ValueError("granete-api.v1.yaml must use OpenAPI 3.1")
    schemas=spec.get("components",{}).get("schemas",{})
    def walk(value,path="$"):
        if isinstance(value,dict):
            ref=value.get("$ref")
            if ref and ref.startswith("#/components/schemas/") and ref.rsplit("/",1)[-1] not in schemas:
                raise ValueError(f"unresolved schema reference at {path}: {ref}")
            if value.get("type")=="object":
                props=value.get("properties",{})
                missing=set(value.get("required",[]))-set(props)
                if missing: raise ValueError(f"required properties missing at {path}: {sorted(missing)}")
            for key,item in value.items(): walk(item,f"{path}.{key}")
        elif isinstance(value,list):
            for index,item in enumerate(value): walk(item,f"{path}[{index}]")
    walk(spec)

def ref_name(s): return s["$ref"].rsplit("/", 1)[-1]

def ts_type(s):
    if "$ref" in s: return ref_name(s)
    t=s.get("type")
    nullable=isinstance(t,list) and "null" in t
    if isinstance(t,list): t=next(x for x in t if x!="null")
    if "enum" in s: base=" | ".join(json.dumps(x) for x in s["enum"])
    elif t=="string": base="string"
    elif t in ("integer","number"): base="number"
    elif t=="boolean": base="boolean"
    elif t=="array": base=f"ReadonlyArray<{ts_type(s['items'])}>"
    elif t=="object":
        additional=s.get("additionalProperties", True)
        value=ts_type(additional) if isinstance(additional,dict) else "unknown"
        base=f"Record<string, {value}>"
    else: base="unknown"
    return base+(" | null" if nullable else "")

def go_type(s):
    if "$ref" in s: return ref_name(s)
    t=s.get("type")
    nullable=isinstance(t,list) and "null" in t
    if isinstance(t,list): t=next(x for x in t if x!="null")
    if t=="string": base="string"
    elif t=="integer": base="int64"
    elif t=="number": base="float64"
    elif t=="boolean": base="bool"
    elif t=="array": base="[]"+go_type(s["items"])
    elif t=="object":
        additional=s.get("additionalProperties", True)
        value=go_type(additional) if isinstance(additional,dict) else "any"
        base=f"map[string]{value}"
    else: base="any"
    if nullable and not base.startswith("[]"): base="*"+base
    return base

def pascal(name):
    special={"id":"ID","url":"URL","ip":"IP"}
    return "".join(special.get(x,x[:1].upper()+x[1:]) for x in re.split(r"[_:-]",name))

def generate_ts(schemas):
    out=["// Code generated by scripts/generate_openapi.py; DO NOT EDIT.\n"]
    for name,s in schemas.items():
        if "enum" in s:
            out.append(f"export type {name} = {ts_type(s)};\n")
        elif s.get("type")=="object":
            req=set(s.get("required",[])); out.append(f"export interface {name} {{")
            for p,ps in s.get("properties",{}).items(): out.append(f"  readonly {json.dumps(p)}{'?' if p not in req else ''}: {ts_type(ps)};")
            out.append("}\n")
    out.append("export const runtimeSchemas = "+json.dumps(schemas,sort_keys=True,separators=(",",":"))+" as const;\n")
    out.append(r'''
function fail(path: string, expected: string): never { throw new Error(`Invalid API response at ${path}: expected ${expected}`); }
function validate(schema: any, value: unknown, path: string): unknown {
  if (schema.$ref) return validate((runtimeSchemas as any)[schema.$ref.split('/').at(-1)!], value, path);
  const types = Array.isArray(schema.type) ? schema.type : [schema.type];
  if (value === null && types.includes('null')) return value;
  const type = types.find((candidate: string) => candidate !== 'null');
  if (schema.enum && !schema.enum.includes(value)) fail(path, schema.enum.join(' | '));
  if (type === 'string') {
    if (typeof value !== 'string') fail(path, 'string');
    if (schema.minLength !== undefined && value.length < schema.minLength) fail(path, `minLength ${schema.minLength}`);
    if (schema.maxLength !== undefined && value.length > schema.maxLength) fail(path, `maxLength ${schema.maxLength}`);
    if (schema.pattern !== undefined && !(new RegExp(schema.pattern)).test(value)) fail(path, `pattern ${schema.pattern}`);
    if (schema.format === 'date-time' && !/^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}(?:\.\d+)?(?:Z|[+-]\d{2}:\d{2})$/.test(value)) fail(path, 'date-time');
    if (schema.format === 'date-time' && Number.isNaN(Date.parse(value))) fail(path, 'date-time');
  }
  if (type === 'integer' || type === 'number') {
    if (typeof value !== 'number' || !Number.isFinite(value) || (type === 'integer' && !Number.isInteger(value))) fail(path, type);
    if (schema.minimum !== undefined && value < schema.minimum) fail(path, `minimum ${schema.minimum}`);
    if (schema.maximum !== undefined && value > schema.maximum) fail(path, `maximum ${schema.maximum}`);
  }
  if (type === 'boolean' && typeof value !== 'boolean') fail(path, 'boolean');
  if (type === 'array') {
    if (!Array.isArray(value)) fail(path, 'array');
    return value.map((item, index) => validate(schema.items, item, `${path}[${index}]`));
  }
  if (type === 'object') {
    if (typeof value !== 'object' || value === null || Array.isArray(value)) fail(path, 'object');
    const input = value as Record<string, unknown>;
    for (const required of schema.required ?? []) if (!(required in input)) fail(`${path}.${required}`, 'required property');
    for (const key of Object.keys(input)) {
      if (key in (schema.properties ?? {})) continue;
      if (schema.additionalProperties === false) fail(`${path}.${key}`, 'no additional property');
      if (schema.additionalProperties && typeof schema.additionalProperties === 'object') validate(schema.additionalProperties, input[key], `${path}.${key}`);
    }
    for (const [key, property] of Object.entries(schema.properties ?? {})) if (key in input) validate(property, input[key], `${path}.${key}`);
  }
  return value;
}
export function parseGenerated<T>(schemaName: keyof typeof runtimeSchemas, value: unknown): T {
  return validate(runtimeSchemas[schemaName], value, '$') as T;
}
export function parseGeneratedArray<T>(schemaName: keyof typeof runtimeSchemas, value: unknown): ReadonlyArray<T> {
  return validate({ type: 'array', items: { $ref: `#/components/schemas/${schemaName}` } }, value, '$') as ReadonlyArray<T>;
}
''')
    return "\n".join(out)

def generate_go(schemas):
    out=["// Code generated by scripts/generate_openapi.py; DO NOT EDIT.","package generated",""]
    for name,s in schemas.items():
        if "enum" in s:
            out.append(f"type {name} string\n\nconst (")
            for v in s["enum"]: out.append(f"\t{name}{pascal(v.lower())} {name} = {json.dumps(v)}")
            out.append(")\n")
        elif s.get("type")=="object":
            req=set(s.get("required",[])); out.append(f"type {name} struct {{")
            for p,ps in s.get("properties",{}).items():
                typ=go_type(ps)
                if p not in req and not typ.startswith(("[]","*","map[")): typ="*"+typ
                out.append(f"\t{pascal(p)} {typ} `json:\"{p}{'' if p in req else ',omitempty'}\"`")
            out.append("}\n")
    return "\n".join(out)

HTTP_METHODS=("get","post","put","patch","delete","options","head","trace")

def resolve_ref(spec, value):
    if not isinstance(value,dict) or "$ref" not in value: return value
    current=spec
    for part in value["$ref"].removeprefix("#/").split("/"): current=current[part]
    return current

def response_schema(operation):
    for status,response in sorted(operation.get("responses",{}).items()):
        if str(status).startswith("2"):
            return response.get("content",{}).get("application/json",{}).get("schema")
    return None

def schema_type_name(schema):
    if "$ref" in schema: return ref_name(schema), "schema"
    if schema.get("type")=="array" and "$ref" in schema.get("items",{}):
        return ref_name(schema["items"]), "arrayOf"
    raise ValueError("generated client responses must be a schema ref or array of schema refs")

def effective_security(spec, operation):
    return operation.get("security", spec.get("security", []))

def generate_path_expression(path, parameters):
    if "{" not in path: return json.dumps(path)
    expression=path
    for parameter in parameters:
        if parameter.get("in")=="path":
            name=parameter["name"]
            expression=expression.replace("{"+name+"}", "${encodeURIComponent("+name+")}")
    return "`"+expression+"`"

def generate_ts_client(spec):
    operations=[]; imports=set()
    for path,path_item in spec.get("paths",{}).items():
        for method in HTTP_METHODS:
            if method not in path_item: continue
            operation=path_item[method]
            operation_id=operation["operationId"]
            parameters=[resolve_ref(spec,p) for p in path_item.get("parameters",[])+operation.get("parameters",[])]
            request_schema=operation.get("requestBody",{}).get("content",{}).get("application/json",{}).get("schema")
            response=response_schema(operation)
            if response is None: raise ValueError(f"{operation_id} needs a successful JSON response schema")
            response_name,response_option=schema_type_name(response); imports.add(response_name)
            args=[]; options=[]
            if effective_security(spec,operation): args.append("token: string"); options.append("token")
            for parameter in parameters:
                if parameter.get("in")=="path": args.append(f"{parameter['name']}: {ts_type(parameter['schema'])}")
            if any(p.get("name")=="If-Match" for p in parameters): args.append("version: number"); options.append("ifMatch: version")
            if request_schema:
                request_type=ts_type(request_schema)
                if "$ref" in request_schema:
                    imports.add(ref_name(request_schema)); options.append(f"bodySchema: {json.dumps(ref_name(request_schema))}")
                args.append(f"body: {request_type}"); options.append("body")
            if any(p.get("name")=="Idempotency-Key" for p in parameters):
                args.append("key = this.createIdempotencyKey()"); options.append("idempotencyKey: key")
            return_type=(f"ReadonlyArray<{response_name}>" if response_option=="arrayOf" else response_name)
            request_options=[f"{response_option}: {json.dumps(response_name)}",*options]
            operations.append(
                f"  {operation_id}({', '.join(args)}): Promise<{return_type}> {{ "
                f"return this.request({json.dumps(method.upper())}, {generate_path_expression(path,parameters)}, "
                f"{{ {', '.join(request_options)} }}); }}"
            )
    imports_block=",\n  ".join(sorted(imports))
    return "\n".join([
        "// Code generated by scripts/generate_openapi.py; DO NOT EDIT.",
        "import type {",f"  {imports_block},","} from './types';","",
        "export interface GeneratedRequestOptions {",
        "  readonly schema?: string;","  readonly arrayOf?: string;","  readonly token?: string;",
        "  readonly ifMatch?: number;","  readonly idempotencyKey?: string;","  readonly bodySchema?: string;","  readonly body?: unknown;","}","",
        "export abstract class GeneratedGraneteApiClient {",
        "  protected abstract request<T>(method: string, path: string, options?: GeneratedRequestOptions): Promise<T>;",
        "  protected abstract createIdempotencyKey(): string;","",*operations,"}",
    ])

def main():
    ap=argparse.ArgumentParser();ap.add_argument("--out-root",type=pathlib.Path,default=ROOT);ap.add_argument("--spec",type=pathlib.Path,default=SPEC);args=ap.parse_args()
    spec=json.loads(args.spec.read_text()); validate_spec(spec); schemas=spec["components"]["schemas"]
    targets=[
      (args.out_root/"packages/storage/src/openapi/generated/types.ts",generate_ts(schemas)),
      (args.out_root/"packages/storage/src/openapi/generated/client.ts",generate_ts_client(spec)),
      (args.out_root/"backend-go/internal/api/openapi/generated/types.gen.go",generate_go(schemas)),
    ]
    for path,content in targets: path.parent.mkdir(parents=True,exist_ok=True);path.write_text(content.rstrip()+"\n")
    subprocess.run(["gofmt", "-w", str(targets[2][0])], check=True)

if __name__=="__main__": main()
