#!/usr/bin/env python3
"""Deterministic, dependency-free generator for Granete's bounded OpenAPI v1."""
from __future__ import annotations
import argparse, json, pathlib, re, subprocess

ROOT = pathlib.Path(__file__).resolve().parents[1]
SPEC = ROOT / "contracts/openapi/granete-api.v1.yaml"

def validate_spec(spec):
    if not str(spec.get("openapi", "")).startswith("3.1."):
        raise ValueError("granete-api.v1.yaml must use OpenAPI 3.1")
    schemas=spec.get("components",{}).get("schemas",{})
    def walk(value,path="$"):
        if isinstance(value,dict):
            ref=value.get("$ref")
            if ref and ref.startswith("#/components/schemas/") and ref.rsplit("/",1)[-1] not in schemas:
                raise ValueError(f"unresolved schema reference at {path}: {ref}")
            if value.get("type")=="object":
                props=value.get("properties",{})
                missing=set(value.get("required",[]))-set(props)
                if missing: raise ValueError(f"required properties missing at {path}: {sorted(missing)}")
            for key,item in value.items(): walk(item,f"{path}.{key}")
        elif isinstance(value,list):
            for index,item in enumerate(value): walk(item,f"{path}[{index}]")
    walk(spec)

def ref_name(s): return s["$ref"].rsplit("/", 1)[-1]

def ts_type(s):
    if "$ref" in s: return ref_name(s)
    t=s.get("type")
    nullable=isinstance(t,list) and "null" in t
    if isinstance(t,list): t=next(x for x in t if x!="null")
    if "enum" in s: base=" | ".join(json.dumps(x) for x in s["enum"])
    elif t=="string": base="string"
    elif t in ("integer","number"): base="number"
    elif t=="boolean": base="boolean"
    elif t=="array": base=f"ReadonlyArray<{ts_type(s['items'])}>"
    elif t=="object": base="Record<string, unknown>"
    else: base="unknown"
    return base+(" | null" if nullable else "")

def go_type(s):
    if "$ref" in s: return ref_name(s)
    t=s.get("type")
    nullable=isinstance(t,list) and "null" in t
    if isinstance(t,list): t=next(x for x in t if x!="null")
    if t=="string": base="string"
    elif t=="integer": base="int64"
    elif t=="number": base="float64"
    elif t=="boolean": base="bool"
    elif t=="array": base="[]"+go_type(s["items"])
    elif t=="object": base="map[string]any"
    else: base="any"
    if nullable and not base.startswith("[]"): base="*"+base
    return base

def pascal(name):
    special={"id":"ID","url":"URL","ip":"IP"}
    return "".join(special.get(x,x[:1].upper()+x[1:]) for x in re.split(r"[_-]",name))

def generate_ts(schemas):
    out=["// Code generated by scripts/generate_openapi.py; DO NOT EDIT.\n"]
    for name,s in schemas.items():
        if "enum" in s:
            out.append(f"export type {name} = {ts_type(s)};\n")
        elif s.get("type")=="object":
            req=set(s.get("required",[])); out.append(f"export interface {name} {{")
            for p,ps in s.get("properties",{}).items(): out.append(f"  readonly {json.dumps(p)}{'?' if p not in req else ''}: {ts_type(ps)};")
            out.append("}\n")
    out.append("export const runtimeSchemas = "+json.dumps(schemas,sort_keys=True,separators=(",",":"))+" as const;\n")
    out.append(r'''
function fail(path: string, expected: string): never { throw new Error(`Invalid API response at ${path}: expected ${expected}`); }
function validate(schema: any, value: unknown, path: string): unknown {
  if (schema.$ref) return validate((runtimeSchemas as any)[schema.$ref.split('/').at(-1)!], value, path);
  const types = Array.isArray(schema.type) ? schema.type : [schema.type];
  if (value === null && types.includes('null')) return value;
  const type = types.find((candidate: string) => candidate !== 'null');
  if (schema.enum && !schema.enum.includes(value)) fail(path, schema.enum.join(' | '));
  if (type === 'string' && typeof value !== 'string') fail(path, 'string');
  if ((type === 'integer' || type === 'number') && (typeof value !== 'number' || !Number.isFinite(value) || (type === 'integer' && !Number.isInteger(value)))) fail(path, type);
  if (type === 'boolean' && typeof value !== 'boolean') fail(path, 'boolean');
  if (type === 'array') {
    if (!Array.isArray(value)) fail(path, 'array');
    return value.map((item, index) => validate(schema.items, item, `${path}[${index}]`));
  }
  if (type === 'object') {
    if (typeof value !== 'object' || value === null || Array.isArray(value)) fail(path, 'object');
    const input = value as Record<string, unknown>;
    for (const required of schema.required ?? []) if (!(required in input)) fail(`${path}.${required}`, 'required property');
    if (schema.additionalProperties === false) for (const key of Object.keys(input)) if (!(key in (schema.properties ?? {}))) fail(`${path}.${key}`, 'no additional property');
    for (const [key, property] of Object.entries(schema.properties ?? {})) if (key in input) validate(property, input[key], `${path}.${key}`);
  }
  return value;
}
export function parseGenerated<T>(schemaName: keyof typeof runtimeSchemas, value: unknown): T {
  return validate(runtimeSchemas[schemaName], value, '$') as T;
}
export function parseGeneratedArray<T>(schemaName: keyof typeof runtimeSchemas, value: unknown): ReadonlyArray<T> {
  return validate({ type: 'array', items: { $ref: `#/components/schemas/${schemaName}` } }, value, '$') as ReadonlyArray<T>;
}
''')
    return "\n".join(out)

def generate_go(schemas):
    out=["// Code generated by scripts/generate_openapi.py; DO NOT EDIT.","package generated",""]
    for name,s in schemas.items():
        if "enum" in s:
            out.append(f"type {name} string\n\nconst (")
            for v in s["enum"]: out.append(f"\t{name}{pascal(v.lower())} {name} = {json.dumps(v)}")
            out.append(")\n")
        elif s.get("type")=="object":
            req=set(s.get("required",[])); out.append(f"type {name} struct {{")
            for p,ps in s.get("properties",{}).items():
                typ=go_type(ps)
                if p not in req and not typ.startswith(("[]","*","map[")): typ="*"+typ
                out.append(f"\t{pascal(p)} {typ} `json:\"{p}{'' if p in req else ',omitempty'}\"`")
            out.append("}\n")
    return "\n".join(out)

def generate_ts_client():
    return r'''// Code generated by scripts/generate_openapi.py; DO NOT EDIT.
import type {
  AcceptInvitationRequest, CreateInvitationRequest, CreateInvitationResponse,
  CreatePlatformOrganizationRequest, EndSupportSessionResponse, Invitation,
  LoginRequest, LoginResponse, MeResponse, MembershipMutationResponse,
  PlatformOrganization, PlatformUser, RegisterRequest, RegisterResponse,
  RevokeInvitationResponse, SecurityAuditEvent, SelectOrganizationRequest,
  SupportSessionResponse, TeamMember, UpdateMemberActiveRequest,
  UpdateMemberRolesRequest, UpdatePlatformOrganizationRequest,
} from './types';

export interface GeneratedRequestOptions {
  readonly schema?: string;
  readonly arrayOf?: string;
  readonly token?: string;
  readonly ifMatch?: number;
  readonly idempotencyKey?: string;
  readonly body?: unknown;
}

export abstract class GeneratedGraneteApiClient {
  protected abstract request<T>(method: string, path: string, options?: GeneratedRequestOptions): Promise<T>;
  protected abstract createIdempotencyKey(): string;

  login(body: LoginRequest): Promise<LoginResponse> { return this.request('POST','/auth/login',{schema:'LoginResponse',body}); }
  register(body: RegisterRequest): Promise<RegisterResponse> { return this.request('POST','/auth/register',{schema:'RegisterResponse',body}); }
  acceptInvitation(body: AcceptInvitationRequest, key = this.createIdempotencyKey()): Promise<LoginResponse> { return this.request('POST','/auth/accept-invitation',{schema:'LoginResponse',body,idempotencyKey:key}); }
  refresh(token: string): Promise<LoginResponse> { return this.request('POST','/auth/refresh',{schema:'LoginResponse',token}); }
  selectOrganization(token: string, body: SelectOrganizationRequest): Promise<LoginResponse> { return this.request('POST','/auth/select-org',{schema:'LoginResponse',token,body}); }
  me(token: string): Promise<MeResponse> { return this.request('GET','/auth/me',{schema:'MeResponse',token}); }
  listTeam(token: string): Promise<ReadonlyArray<TeamMember>> { return this.request('GET','/org/team',{arrayOf:'TeamMember',token}); }
  listInvitations(token: string): Promise<ReadonlyArray<Invitation>> { return this.request('GET','/org/invitations',{arrayOf:'Invitation',token}); }
  createInvitation(token: string, body: CreateInvitationRequest, key = this.createIdempotencyKey()): Promise<CreateInvitationResponse> { return this.request('POST','/org/invitations',{schema:'CreateInvitationResponse',token,body,idempotencyKey:key}); }
  revokeInvitation(token: string, invitationId: string): Promise<RevokeInvitationResponse> { return this.request('DELETE',`/org/invitations/${encodeURIComponent(invitationId)}`,{schema:'RevokeInvitationResponse',token}); }
  updateMemberRoles(token: string, userId: string, version: number, body: UpdateMemberRolesRequest): Promise<MembershipMutationResponse> { return this.request('PUT',`/org/members/${encodeURIComponent(userId)}/roles`,{schema:'MembershipMutationResponse',token,ifMatch:version,body}); }
  updateMemberActive(token: string, userId: string, version: number, body: UpdateMemberActiveRequest): Promise<MembershipMutationResponse> { return this.request('PUT',`/org/members/${encodeURIComponent(userId)}/active`,{schema:'MembershipMutationResponse',token,ifMatch:version,body}); }
  listPlatformOrganizations(token: string): Promise<ReadonlyArray<PlatformOrganization>> { return this.request('GET','/platform/organizations',{arrayOf:'PlatformOrganization',token}); }
  createPlatformOrganization(token: string, body: CreatePlatformOrganizationRequest, key = this.createIdempotencyKey()): Promise<PlatformOrganization> { return this.request('POST','/platform/organizations',{schema:'PlatformOrganization',token,body,idempotencyKey:key}); }
  listPlatformUsers(token: string): Promise<ReadonlyArray<PlatformUser>> { return this.request('GET','/platform/users',{arrayOf:'PlatformUser',token}); }
  listSecurityAudit(token: string, organizationId: string): Promise<ReadonlyArray<SecurityAuditEvent>> { return this.request('GET',`/platform/organizations/${encodeURIComponent(organizationId)}/audit?limit=100`,{arrayOf:'SecurityAuditEvent',token}); }
  updatePlatformOrganization(token: string, organizationId: string, version: number, body: UpdatePlatformOrganizationRequest): Promise<PlatformOrganization> { return this.request('PATCH',`/platform/organizations/${encodeURIComponent(organizationId)}`,{schema:'PlatformOrganization',token,ifMatch:version,body}); }
  startSupportSession(token: string, organizationId: string, reason: string, key = this.createIdempotencyKey()): Promise<SupportSessionResponse> { return this.request('POST',`/platform/organizations/${encodeURIComponent(organizationId)}/support-session`,{schema:'SupportSessionResponse',token,idempotencyKey:key,body:{reason}}); }
  endSupportSession(token: string, sessionId: string): Promise<EndSupportSessionResponse> { return this.request('DELETE',`/platform/support-sessions/${encodeURIComponent(sessionId)}`,{schema:'EndSupportSessionResponse',token}); }
}
'''

def main():
    ap=argparse.ArgumentParser();ap.add_argument("--out-root",type=pathlib.Path,default=ROOT);args=ap.parse_args()
    spec=json.loads(SPEC.read_text()); validate_spec(spec); schemas=spec["components"]["schemas"]
    targets=[
      (args.out_root/"packages/storage/src/openapi/generated/types.ts",generate_ts(schemas)),
      (args.out_root/"packages/storage/src/openapi/generated/client.ts",generate_ts_client()),
      (args.out_root/"backend-go/internal/api/openapi/generated/types.gen.go",generate_go(schemas)),
    ]
    for path,content in targets: path.parent.mkdir(parents=True,exist_ok=True);path.write_text(content+"\n")
    subprocess.run(["gofmt", "-w", str(targets[2][0])], check=True)

if __name__=="__main__": main()
