# frozen_string_literal: true

source 'https://rubygems.org'

group :development do
  gem 'minitest', '~> 5.15'
  gem 'rake'
  gem 'rubyzip', '~> 3.5', require: false
  gem 'sketchup-api-stubs'
  gem 'skippy', '~> 0.5.3.a'
  gem 'solargraph'
end

group :documentation do
  gem 'commonmarker', '~> 0.23'
  gem 'yard', '~> 0.9'
end

group :analysis do
  gem 'rubocop', '>= 1.85', '< 2.0'
  gem 'rubocop-sketchup', '~> 2.1.1'
end
