name: Cleanup Old Workflow Runs

on:
  schedule:
    # Se ejecuta todos los días a las 00:00 UTC
    - cron: '0 0 * * *'
  # Permite dispararlo manualmente desde la pestaña Actions cuando quieras
  workflow_dispatch:

jobs:
  delete-runs:
    runs-on: ubuntu-latest
    permissions:
      actions: write
      contents: read
    steps:
      - name: Delete runs older than 7 days
        uses: Mattraks/delete-workflow-runs@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          repository: ${{ github.repository }}
          retain_days: 7
          keep_minimum_runs: 3 # Mantiene al menos las últimas 3 ejecuciones por seguridad
